// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: host.sql

package sqlitesqlc

import (
	"context"
	"database/sql"
	"time"
)

const countHosts = `-- name: CountHosts :one
SELECT COUNT(*) FROM hosts
`

func (q *Queries) CountHosts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countHosts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createHost = `-- name: CreateHost :exec
INSERT INTO hosts (
    id, created_at, updated_at, name, os, agent_version,
    last_seen_at, last_cpu_pct, last_mem_pct, last_disk_pct,
    last_net_in, last_net_out, last_disks
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateHostParams struct {
	ID           string          `json:"id"`
	CreatedAt    time.Time       `json:"created_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
	Name         string          `json:"name"`
	Os           sql.NullString  `json:"os"`
	AgentVersion sql.NullString  `json:"agent_version"`
	LastSeenAt   sql.NullTime    `json:"last_seen_at"`
	LastCpuPct   sql.NullFloat64 `json:"last_cpu_pct"`
	LastMemPct   sql.NullFloat64 `json:"last_mem_pct"`
	LastDiskPct  sql.NullFloat64 `json:"last_disk_pct"`
	LastNetIn    sql.NullInt64   `json:"last_net_in"`
	LastNetOut   sql.NullInt64   `json:"last_net_out"`
	LastDisks    sql.NullString  `json:"last_disks"`
}

func (q *Queries) CreateHost(ctx context.Context, arg CreateHostParams) error {
	_, err := q.db.ExecContext(ctx, createHost,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.Os,
		arg.AgentVersion,
		arg.LastSeenAt,
		arg.LastCpuPct,
		arg.LastMemPct,
		arg.LastDiskPct,
		arg.LastNetIn,
		arg.LastNetOut,
		arg.LastDisks,
	)
	return err
}

const deleteHost = `-- name: DeleteHost :execrows
DELETE FROM hosts WHERE id = ?
`

func (q *Queries) DeleteHost(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteHost, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const findHostByID = `-- name: FindHostByID :one
SELECT id, created_at, updated_at, name, os, agent_version, last_seen_at, last_cpu_pct, last_mem_pct, last_disk_pct, last_net_in, last_net_out, last_disks FROM hosts WHERE id = ?
`

func (q *Queries) FindHostByID(ctx context.Context, id string) (Host, error) {
	row := q.db.QueryRowContext(ctx, findHostByID, id)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Os,
		&i.AgentVersion,
		&i.LastSeenAt,
		&i.LastCpuPct,
		&i.LastMemPct,
		&i.LastDiskPct,
		&i.LastNetIn,
		&i.LastNetOut,
		&i.LastDisks,
	)
	return i, err
}

const listHosts = `-- name: ListHosts :many
SELECT id, created_at, updated_at, name, os, agent_version, last_seen_at, last_cpu_pct, last_mem_pct, last_disk_pct, last_net_in, last_net_out, last_disks FROM hosts
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListHostsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListHosts(ctx context.Context, arg ListHostsParams) ([]Host, error) {
	rows, err := q.db.QueryContext(ctx, listHosts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Host{}
	for rows.Next() {
		var i Host
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Os,
			&i.AgentVersion,
			&i.LastSeenAt,
			&i.LastCpuPct,
			&i.LastMemPct,
			&i.LastDiskPct,
			&i.LastNetIn,
			&i.LastNetOut,
			&i.LastDisks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHostSnapshot = `-- name: UpdateHostSnapshot :execrows
UPDATE hosts
SET last_seen_at  = ?2,
    last_cpu_pct  = ?3,
    last_mem_pct  = ?4,
    last_disk_pct = ?5,
    last_net_in   = ?6,
    last_net_out  = ?7,
    last_disks    = ?8,
    os            = COALESCE(?9, os),
    agent_version = COALESCE(?10, agent_version),
    updated_at    = ?11
WHERE id = ?1
`

type UpdateHostSnapshotParams struct {
	ID           string          `json:"id"`
	LastSeenAt   sql.NullTime    `json:"last_seen_at"`
	LastCpuPct   sql.NullFloat64 `json:"last_cpu_pct"`
	LastMemPct   sql.NullFloat64 `json:"last_mem_pct"`
	LastDiskPct  sql.NullFloat64 `json:"last_disk_pct"`
	LastNetIn    sql.NullInt64   `json:"last_net_in"`
	LastNetOut   sql.NullInt64   `json:"last_net_out"`
	LastDisks    sql.NullString  `json:"last_disks"`
	Os           sql.NullString  `json:"os"`
	AgentVersion sql.NullString  `json:"agent_version"`
	UpdatedAt    time.Time       `json:"updated_at"`
}

func (q *Queries) UpdateHostSnapshot(ctx context.Context, arg UpdateHostSnapshotParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateHostSnapshot,
		arg.ID,
		arg.LastSeenAt,
		arg.LastCpuPct,
		arg.LastMemPct,
		arg.LastDiskPct,
		arg.LastNetIn,
		arg.LastNetOut,
		arg.LastDisks,
		arg.Os,
		arg.AgentVersion,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
