// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: host_metric.sql

package sqlitesqlc

import (
	"context"
	"database/sql"
	"time"
)

const decimateHostMetrics = `-- name: DecimateHostMetrics :execrows
DELETE FROM host_metrics
WHERE host_metrics.sampled_at < ?1
  AND host_metrics.id NOT IN (
    SELECT MIN(hm.id) FROM host_metrics hm
    WHERE hm.sampled_at < ?1
    GROUP BY hm.host_id, substr(hm.sampled_at, 1, 16)
  )
`

// Keep at most one sample per (host, minute) for rows older than the cutoff,
// deleting the rest. MIN(id) is the earliest ULID in each minute bucket;
// substr(sampled_at,1,16) buckets by 'YYYY-MM-DD HH:MM'.
func (q *Queries) DecimateHostMetrics(ctx context.Context, sampledAt time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, decimateHostMetrics, sampledAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteHostMetricsByHost = `-- name: DeleteHostMetricsByHost :exec
DELETE FROM host_metrics WHERE host_id = ?
`

func (q *Queries) DeleteHostMetricsByHost(ctx context.Context, hostID string) error {
	_, err := q.db.ExecContext(ctx, deleteHostMetricsByHost, hostID)
	return err
}

const deleteHostMetricsOlderThan = `-- name: DeleteHostMetricsOlderThan :execrows
DELETE FROM host_metrics WHERE sampled_at < ?1
`

func (q *Queries) DeleteHostMetricsOlderThan(ctx context.Context, sampledAt time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteHostMetricsOlderThan, sampledAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertHostMetric = `-- name: InsertHostMetric :exec
INSERT INTO host_metrics (
    id, host_id, sampled_at, cpu_pct, mem_pct, net_in, net_out, disks
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertHostMetricParams struct {
	ID        string         `json:"id"`
	HostID    string         `json:"host_id"`
	SampledAt time.Time      `json:"sampled_at"`
	CpuPct    float64        `json:"cpu_pct"`
	MemPct    float64        `json:"mem_pct"`
	NetIn     int64          `json:"net_in"`
	NetOut    int64          `json:"net_out"`
	Disks     sql.NullString `json:"disks"`
}

func (q *Queries) InsertHostMetric(ctx context.Context, arg InsertHostMetricParams) error {
	_, err := q.db.ExecContext(ctx, insertHostMetric,
		arg.ID,
		arg.HostID,
		arg.SampledAt,
		arg.CpuPct,
		arg.MemPct,
		arg.NetIn,
		arg.NetOut,
		arg.Disks,
	)
	return err
}

const listHostMetricsInRange = `-- name: ListHostMetricsInRange :many
SELECT id, host_id, sampled_at, cpu_pct, mem_pct, net_in, net_out, disks FROM host_metrics
WHERE host_id = ?1 AND sampled_at >= ?2 AND sampled_at <= ?3
ORDER BY sampled_at ASC
`

type ListHostMetricsInRangeParams struct {
	HostID      string    `json:"host_id"`
	SampledAt   time.Time `json:"sampled_at"`
	SampledAt_2 time.Time `json:"sampled_at_2"`
}

func (q *Queries) ListHostMetricsInRange(ctx context.Context, arg ListHostMetricsInRangeParams) ([]HostMetric, error) {
	rows, err := q.db.QueryContext(ctx, listHostMetricsInRange, arg.HostID, arg.SampledAt, arg.SampledAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HostMetric{}
	for rows.Next() {
		var i HostMetric
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.SampledAt,
			&i.CpuPct,
			&i.MemPct,
			&i.NetIn,
			&i.NetOut,
			&i.Disks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
