// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlitesqlc

import (
	"database/sql"
	"time"
)

type Announcement struct {
	ID          string    `json:"id"`
	Severity    string    `json:"severity"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Dismissible int64     `json:"dismissible"`
	Active      int64     `json:"active"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type ApiKey struct {
	ID         string       `json:"id"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
	UserID     string       `json:"user_id"`
	Name       string       `json:"name"`
	KeyHash    string       `json:"key_hash"`
	KeyPrefix  string       `json:"key_prefix"`
	Scope      string       `json:"scope"`
	ExpiresAt  sql.NullTime `json:"expires_at"`
	LastUsedAt sql.NullTime `json:"last_used_at"`
	LastUsedIp string       `json:"last_used_ip"`
	IsActive   int64        `json:"is_active"`
}

type Component struct {
	ID                     string         `json:"id"`
	CreatedAt              time.Time      `json:"created_at"`
	UpdatedAt              time.Time      `json:"updated_at"`
	Name                   string         `json:"name"`
	Description            sql.NullString `json:"description"`
	LastNotificationStatus string         `json:"last_notification_status"`
	GroupingWindowSeconds  int64          `json:"grouping_window_seconds"`
}

type ComponentNotificationChannel struct {
	ComponentID           string `json:"component_id"`
	NotificationChannelID string `json:"notification_channel_id"`
}

type Dashboard struct {
	ID               string    `json:"id"`
	OwnerID          string    `json:"owner_id"`
	Name             string    `json:"name"`
	Scope            string    `json:"scope"`
	Widgets          string    `json:"widgets"`
	DefaultTimeRange string    `json:"default_time_range"`
	RefreshInterval  string    `json:"refresh_interval"`
	Visibility       string    `json:"visibility"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type EscalationPolicy struct {
	ID         string    `json:"id"`
	Name       string    `json:"name"`
	ScopeKind  string    `json:"scope_kind"`
	ScopeValue string    `json:"scope_value"`
	IsActive   int64     `json:"is_active"`
	Priority   int64     `json:"priority"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type EscalationStep struct {
	ID           string `json:"id"`
	PolicyID     string `json:"policy_id"`
	StepOrder    int64  `json:"step_order"`
	DelayMinutes int64  `json:"delay_minutes"`
	ChannelIds   string `json:"channel_ids"`
}

type ExpiryNotificationLog struct {
	ID         string    `json:"id"`
	ResourceID string    `json:"resource_id"`
	ExpiryType string    `json:"expiry_type"`
	Threshold  int64     `json:"threshold"`
	SentAt     time.Time `json:"sent_at"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type Host struct {
	ID           string          `json:"id"`
	CreatedAt    time.Time       `json:"created_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
	Name         string          `json:"name"`
	Os           sql.NullString  `json:"os"`
	AgentVersion sql.NullString  `json:"agent_version"`
	LastSeenAt   sql.NullTime    `json:"last_seen_at"`
	LastCpuPct   sql.NullFloat64 `json:"last_cpu_pct"`
	LastMemPct   sql.NullFloat64 `json:"last_mem_pct"`
	LastDiskPct  sql.NullFloat64 `json:"last_disk_pct"`
	LastNetIn    sql.NullInt64   `json:"last_net_in"`
	LastNetOut   sql.NullInt64   `json:"last_net_out"`
	LastDisks    sql.NullString  `json:"last_disks"`
}

type HostCredential struct {
	ID         string       `json:"id"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
	HostID     string       `json:"host_id"`
	Hash       string       `json:"hash"`
	Prefix     string       `json:"prefix"`
	IsActive   int64        `json:"is_active"`
	LastUsedAt sql.NullTime `json:"last_used_at"`
}

type HostMetric struct {
	ID        string         `json:"id"`
	HostID    string         `json:"host_id"`
	SampledAt time.Time      `json:"sampled_at"`
	CpuPct    float64        `json:"cpu_pct"`
	MemPct    float64        `json:"mem_pct"`
	NetIn     int64          `json:"net_in"`
	NetOut    int64          `json:"net_out"`
	Disks     sql.NullString `json:"disks"`
}

type Incident struct {
	ID         string       `json:"id"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
	ResourceID string       `json:"resource_id"`
	Cause      string       `json:"cause"`
	ResolvedAt sql.NullTime `json:"resolved_at"`
	StartedAt  time.Time    `json:"started_at"`
	Details    []byte       `json:"details"`
}

type IncidentDiagnostic struct {
	ID                string         `json:"id"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	IncidentID        string         `json:"incident_id"`
	RequestMethod     string         `json:"request_method"`
	RequestUrl        string         `json:"request_url"`
	RequestHeaders    string         `json:"request_headers"`
	RequestTimeout    int64          `json:"request_timeout"`
	HttpStatusCode    int64          `json:"http_status_code"`
	ResponseHeaders   string         `json:"response_headers"`
	ResponseBody      string         `json:"response_body"`
	ResponseSize      int64          `json:"response_size"`
	FailureType       string         `json:"failure_type"`
	ErrorMessage      string         `json:"error_message"`
	ErrorSummary      string         `json:"error_summary"`
	TotalDuration     int64          `json:"total_duration"`
	DnsDuration       int64          `json:"dns_duration"`
	TlsDuration       int64          `json:"tls_duration"`
	FirstByteDuration int64          `json:"first_byte_duration"`
	BodyTruncated     int64          `json:"body_truncated"`
	BodyEncoded       int64          `json:"body_encoded"`
	IcmpAvailable     sql.NullInt64  `json:"icmp_available"`
	IcmpReachable     sql.NullInt64  `json:"icmp_reachable"`
	IcmpRttMs         sql.NullInt64  `json:"icmp_rtt_ms"`
	RootCauseHint     string         `json:"root_cause_hint"`
	Keyword           sql.NullString `json:"keyword"`
	KeywordMode       sql.NullString `json:"keyword_mode"`
	KeywordFound      sql.NullBool   `json:"keyword_found"`
}

type IncidentEventStep struct {
	ID         string         `json:"id"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
	IncidentID string         `json:"incident_id"`
	Step       string         `json:"step"`
	Message    sql.NullString `json:"message"`
}

type IncidentUpdate struct {
	ID         string    `json:"id"`
	IncidentID string    `json:"incident_id"`
	Status     string    `json:"status"`
	Message    string    `json:"message"`
	PostedBy   string    `json:"posted_by"`
	PostedAt   time.Time `json:"posted_at"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type Maintenance struct {
	ID             string         `json:"id"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	Title          string         `json:"title"`
	Description    sql.NullString `json:"description"`
	Strategy       string         `json:"strategy"`
	Status         string         `json:"status"`
	StartAt        sql.NullTime   `json:"start_at"`
	EndAt          sql.NullTime   `json:"end_at"`
	CronExpr       sql.NullString `json:"cron_expr"`
	WindowMinutes  sql.NullInt64  `json:"window_minutes"`
	Timezone       sql.NullString `json:"timezone"`
	EffectiveFrom  sql.NullTime   `json:"effective_from"`
	EffectiveUntil sql.NullTime   `json:"effective_until"`
	StartedAt      sql.NullTime   `json:"started_at"`
	EndedAt        sql.NullTime   `json:"ended_at"`
}

type MaintenanceResource struct {
	MaintenanceID string `json:"maintenance_id"`
	ResourceID    string `json:"resource_id"`
}

type MonitoringActivity struct {
	ID            string    `json:"id"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
	ResourceID    string    `json:"resource_id"`
	Message       string    `json:"message"`
	Success       int64     `json:"success"`
	ResponseTime  int64     `json:"response_time"`
	ResponseData  []byte    `json:"response_data"`
	IsMaintenance int64     `json:"is_maintenance"`
}

type Notification struct {
	ID          string         `json:"id"`
	UserID      sql.NullString `json:"user_id"`
	Category    string         `json:"category"`
	Severity    string         `json:"severity"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	DeepLink    sql.NullString `json:"deep_link"`
	Payload     sql.NullString `json:"payload"`
	OccurredAt  time.Time      `json:"occurred_at"`
	ReadAt      sql.NullTime   `json:"read_at"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type NotificationChannel struct {
	ID               string      `json:"id"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
	Name             string      `json:"name"`
	Type             string      `json:"type"`
	Config           []byte      `json:"config"`
	EnabledByDefault int64       `json:"enabled_by_default"`
	LastSentAt       interface{} `json:"last_sent_at"`
	LastFailureAt    interface{} `json:"last_failure_at"`
	Failures24h      int64       `json:"failures_24h"`
}

type NotificationEvent struct {
	ID          string         `json:"id"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	IncidentID  string         `json:"incident_id"`
	Type        string         `json:"type"`
	Status      string         `json:"status"`
	ClaimOwner  sql.NullString `json:"claim_owner"`
	ClaimedAt   sql.NullTime   `json:"claimed_at"`
	ProcessedAt sql.NullTime   `json:"processed_at"`
	LastError   string         `json:"last_error"`
}

type ReportHistory struct {
	ID                string    `json:"id"`
	Period            string    `json:"period"`
	SentAt            time.Time `json:"sent_at"`
	Status            string    `json:"status"`
	UptimePct         float64   `json:"uptime_pct"`
	IncidentCount     int64     `json:"incident_count"`
	DowntimeSeconds   int64     `json:"downtime_seconds"`
	RecipientEmail    string    `json:"recipient_email"`
	ResourceBreakdown string    `json:"resource_breakdown"`
	CreatedAt         time.Time `json:"created_at"`
}

type ReportSetting struct {
	ID             string       `json:"id"`
	Enabled        int64        `json:"enabled"`
	RecipientEmail string       `json:"recipient_email"`
	Schedule       string       `json:"schedule"`
	Scope          string       `json:"scope"`
	LastSentAt     sql.NullTime `json:"last_sent_at"`
	CreatedAt      time.Time    `json:"created_at"`
	UpdatedAt      time.Time    `json:"updated_at"`
}

type Resource struct {
	ID                      string         `json:"id"`
	CreatedAt               time.Time      `json:"created_at"`
	UpdatedAt               time.Time      `json:"updated_at"`
	Name                    string         `json:"name"`
	Type                    string         `json:"type"`
	Interval                int64          `json:"interval"`
	Timeout                 int64          `json:"timeout"`
	Target                  string         `json:"target"`
	LastChecked             sql.NullTime   `json:"last_checked"`
	Status                  string         `json:"status"`
	IsActive                int64          `json:"is_active"`
	FailureCount            int64          `json:"failure_count"`
	SslExpirationDate       sql.NullTime   `json:"ssl_expiration_date"`
	SslIssuer               sql.NullString `json:"ssl_issuer"`
	DomainExpirationDate    sql.NullTime   `json:"domain_expiration_date"`
	DomainRegistrar         sql.NullString `json:"domain_registrar"`
	ComponentID             sql.NullString `json:"component_id"`
	ConfirmationChecks      int64          `json:"confirmation_checks"`
	ConfirmationInterval    int64          `json:"confirmation_interval"`
	ExpiryAlertThresholds   sql.NullString `json:"expiry_alert_thresholds"`
	FlapDetectionEnabled    int64          `json:"flap_detection_enabled"`
	FlapThreshold           int64          `json:"flap_threshold"`
	FlapWindowSeconds       int64          `json:"flap_window_seconds"`
	FlapMaxDurationMinutes  int64          `json:"flap_max_duration_minutes"`
	LastStatusTransition    sql.NullTime   `json:"last_status_transition"`
	FlapStartedAt           sql.NullTime   `json:"flap_started_at"`
	ReminderIntervalMinutes int64          `json:"reminder_interval_minutes"`
	HeartbeatSlug           sql.NullString `json:"heartbeat_slug"`
	HeartbeatInterval       sql.NullInt64  `json:"heartbeat_interval"`
	HeartbeatGrace          sql.NullInt64  `json:"heartbeat_grace"`
	LastPingAt              sql.NullTime   `json:"last_ping_at"`
	Keyword                 sql.NullString `json:"keyword"`
	KeywordMode             sql.NullString `json:"keyword_mode"`
	ProtocolType            sql.NullString `json:"protocol_type"`
	ProtocolPort            sql.NullInt64  `json:"protocol_port"`
	HostID                  sql.NullString `json:"host_id"`
}

type ResourceCredential struct {
	ID         string         `json:"id"`
	ResourceID string         `json:"resource_id"`
	Username   sql.NullString `json:"username"`
	Password   []byte         `json:"password"`
	Options    []byte         `json:"options"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

type ResourceNotificationChannel struct {
	ResourceID            string `json:"resource_id"`
	NotificationChannelID string `json:"notification_channel_id"`
}

type ResourceTag struct {
	ResourceID string `json:"resource_id"`
	TagID      string `json:"tag_id"`
}

type SchemaMigration struct {
	Version   string    `json:"version"`
	Name      string    `json:"name"`
	AppliedAt time.Time `json:"applied_at"`
}

type Session struct {
	ID           string         `json:"id"`
	UserID       string         `json:"user_id"`
	Browser      string         `json:"browser"`
	Os           string         `json:"os"`
	Ip           string         `json:"ip"`
	Location     sql.NullString `json:"location"`
	LastActiveAt time.Time      `json:"last_active_at"`
	CreatedAt    time.Time      `json:"created_at"`
	RevokedAt    sql.NullTime   `json:"revoked_at"`
}

type StatusPageSetting struct {
	ID                     string    `json:"id"`
	CreatedAt              time.Time `json:"created_at"`
	UpdatedAt              time.Time `json:"updated_at"`
	Name                   string    `json:"name"`
	HomepageUrl            string    `json:"homepage_url"`
	CustomDomain           string    `json:"custom_domain"`
	GoogleAnalyticsID      string    `json:"google_analytics_id"`
	EnableDetailsPage      int64     `json:"enable_details_page"`
	ShowUptimePercentage   int64     `json:"show_uptime_percentage"`
	HidePausedMonitors     int64     `json:"hide_paused_monitors"`
	ShowIncidentHistory    int64     `json:"show_incident_history"`
	CustomDomainStatus     string    `json:"custom_domain_status"`
	CustomDomainSslStatus  string    `json:"custom_domain_ssl_status"`
	CustomDomainDnsRecords string    `json:"custom_domain_dns_records"`
	LogoUrlLight           string    `json:"logo_url_light"`
	LogoUrlDark            string    `json:"logo_url_dark"`
	FaviconUrl             string    `json:"favicon_url"`
	PrimaryColor           string    `json:"primary_color"`
	ThemeOverrides         string    `json:"theme_overrides"`
	UmamiWebsiteID         string    `json:"umami_website_id"`
	UmamiScriptUrl         string    `json:"umami_script_url"`
}

type Tag struct {
	ID          string         `json:"id"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	Name        string         `json:"name"`
	Color       sql.NullString `json:"color"`
	Description sql.NullString `json:"description"`
}

type TwoFactorResetToken struct {
	TokenHash string       `json:"token_hash"`
	UserID    string       `json:"user_id"`
	ExpiresAt time.Time    `json:"expires_at"`
	UsedAt    sql.NullTime `json:"used_at"`
	CreatedAt time.Time    `json:"created_at"`
}

type UptimeDailyAgg struct {
	ResourceID  string    `json:"resource_id"`
	Day         string    `json:"day"`
	Samples     int64     `json:"samples"`
	Up          int64     `json:"up"`
	Degraded    int64     `json:"degraded"`
	Down        int64     `json:"down"`
	UptimeRatio float64   `json:"uptime_ratio"`
	ComputedAt  time.Time `json:"computed_at"`
}

type User struct {
	ID                   string       `json:"id"`
	Email                string       `json:"email"`
	Name                 string       `json:"name"`
	HashedPassword       string       `json:"hashed_password"`
	PasswordInitialized  int64        `json:"password_initialized"`
	ForcePasswordChange  int64        `json:"force_password_change"`
	TwoFactorEnabled     int64        `json:"two_factor_enabled"`
	TwoFactorSecret      string       `json:"two_factor_secret"`
	TwoFactorBackupCodes []byte       `json:"two_factor_backup_codes"`
	LastLoginAt          sql.NullTime `json:"last_login_at"`
	CreatedAt            time.Time    `json:"created_at"`
	UpdatedAt            time.Time    `json:"updated_at"`
}
