// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification_feed.sql

package sqlitesqlc

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const countNotificationsForUser = `-- name: CountNotificationsForUser :one
SELECT COUNT(*) FROM notifications
WHERE (user_id IS NULL OR user_id = ?1)
  AND (?2 IS NULL OR category = ?2)
`

type CountNotificationsForUserParams struct {
	UserID   sql.NullString `json:"user_id"`
	Category interface{}    `json:"category"`
}

func (q *Queries) CountNotificationsForUser(ctx context.Context, arg CountNotificationsForUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNotificationsForUser, arg.UserID, arg.Category)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnreadForEscalation = `-- name: CountUnreadForEscalation :one
SELECT COUNT(*) FROM notifications
WHERE read_at IS NULL
  AND user_id IS NULL
  AND occurred_at <= ?1
  AND category IN (/*SLICE:categories*/?)
`

type CountUnreadForEscalationParams struct {
	Cutoff     time.Time `json:"cutoff"`
	Categories []string  `json:"categories"`
}

func (q *Queries) CountUnreadForEscalation(ctx context.Context, arg CountUnreadForEscalationParams) (int64, error) {
	query := countUnreadForEscalation
	var queryParams []interface{}
	queryParams = append(queryParams, arg.Cutoff)
	if len(arg.Categories) > 0 {
		for _, v := range arg.Categories {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:categories*/?", strings.Repeat(",?", len(arg.Categories))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:categories*/?", "NULL", 1)
	}
	row := q.db.QueryRowContext(ctx, query, queryParams...)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (id, user_id, category, severity, title, description, deep_link, payload, occurred_at, read_at, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, category, severity, title, description, deep_link, payload, occurred_at, read_at, created_at, updated_at
`

type CreateNotificationParams struct {
	ID          string         `json:"id"`
	UserID      sql.NullString `json:"user_id"`
	Category    string         `json:"category"`
	Severity    string         `json:"severity"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	DeepLink    sql.NullString `json:"deep_link"`
	Payload     sql.NullString `json:"payload"`
	OccurredAt  time.Time      `json:"occurred_at"`
	ReadAt      sql.NullTime   `json:"read_at"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, createNotification,
		arg.ID,
		arg.UserID,
		arg.Category,
		arg.Severity,
		arg.Title,
		arg.Description,
		arg.DeepLink,
		arg.Payload,
		arg.OccurredAt,
		arg.ReadAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Category,
		&i.Severity,
		&i.Title,
		&i.Description,
		&i.DeepLink,
		&i.Payload,
		&i.OccurredAt,
		&i.ReadAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNotificationsOlderThan = `-- name: DeleteNotificationsOlderThan :execrows
DELETE FROM notifications WHERE occurred_at < ?1
`

func (q *Queries) DeleteNotificationsOlderThan(ctx context.Context, cutoff time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteNotificationsOlderThan, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listNotificationsForUser = `-- name: ListNotificationsForUser :many
SELECT id, user_id, category, severity, title, description, deep_link, payload, occurred_at, read_at, created_at, updated_at FROM notifications
WHERE (user_id IS NULL OR user_id = ?1)
  AND (?2 IS NULL OR category = ?2)
ORDER BY occurred_at DESC
LIMIT ?4 OFFSET ?3
`

type ListNotificationsForUserParams struct {
	UserID   sql.NullString `json:"user_id"`
	Category interface{}    `json:"category"`
	Off      int64          `json:"off"`
	Lim      int64          `json:"lim"`
}

func (q *Queries) ListNotificationsForUser(ctx context.Context, arg ListNotificationsForUserParams) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationsForUser,
		arg.UserID,
		arg.Category,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Category,
			&i.Severity,
			&i.Title,
			&i.Description,
			&i.DeepLink,
			&i.Payload,
			&i.OccurredAt,
			&i.ReadAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreadForEscalation = `-- name: ListUnreadForEscalation :many
SELECT id, user_id, category, severity, title, description, deep_link, payload, occurred_at, read_at, created_at, updated_at FROM notifications
WHERE read_at IS NULL
  AND user_id IS NULL
  AND occurred_at <= ?1
  AND category IN (/*SLICE:categories*/?)
ORDER BY occurred_at DESC
`

type ListUnreadForEscalationParams struct {
	Cutoff     time.Time `json:"cutoff"`
	Categories []string  `json:"categories"`
}

func (q *Queries) ListUnreadForEscalation(ctx context.Context, arg ListUnreadForEscalationParams) ([]Notification, error) {
	query := listUnreadForEscalation
	var queryParams []interface{}
	queryParams = append(queryParams, arg.Cutoff)
	if len(arg.Categories) > 0 {
		for _, v := range arg.Categories {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:categories*/?", strings.Repeat(",?", len(arg.Categories))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:categories*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Category,
			&i.Severity,
			&i.Title,
			&i.Description,
			&i.DeepLink,
			&i.Payload,
			&i.OccurredAt,
			&i.ReadAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsReadForUser = `-- name: MarkAllNotificationsReadForUser :execrows
UPDATE notifications
SET read_at = ?1, updated_at = ?2
WHERE read_at IS NULL
  AND occurred_at <= ?3
  AND (user_id IS NULL OR user_id = ?4)
`

type MarkAllNotificationsReadForUserParams struct {
	ReadAt    sql.NullTime   `json:"read_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	BeforeTs  time.Time      `json:"before_ts"`
	UserID    sql.NullString `json:"user_id"`
}

func (q *Queries) MarkAllNotificationsReadForUser(ctx context.Context, arg MarkAllNotificationsReadForUserParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markAllNotificationsReadForUser,
		arg.ReadAt,
		arg.UpdatedAt,
		arg.BeforeTs,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markNotificationRead = `-- name: MarkNotificationRead :execrows
UPDATE notifications
SET read_at = COALESCE(read_at, ?1), updated_at = ?2
WHERE id = ?3
`

type MarkNotificationReadParams struct {
	ReadAt    sql.NullTime `json:"read_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	ID        string       `json:"id"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markNotificationRead, arg.ReadAt, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
