// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: resource.sql

package sqlitesqlc

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const clearResourceHostIDByHost = `-- name: ClearResourceHostIDByHost :exec
UPDATE resources SET host_id = NULL WHERE host_id = ?
`

func (q *Queries) ClearResourceHostIDByHost(ctx context.Context, hostID sql.NullString) error {
	_, err := q.db.ExecContext(ctx, clearResourceHostIDByHost, hostID)
	return err
}

const countResourcesByComponentID = `-- name: CountResourcesByComponentID :one
SELECT COUNT(*) FROM resources
WHERE component_id = ? AND is_active = 1
`

func (q *Queries) CountResourcesByComponentID(ctx context.Context, componentID sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countResourcesByComponentID, componentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createResource = `-- name: CreateResource :exec

INSERT INTO resources (
    id, created_at, updated_at, name, type, interval, timeout, target,
    last_checked, status, is_active, failure_count,
    ssl_expiration_date, ssl_issuer, domain_expiration_date, domain_registrar,
    component_id, confirmation_checks, confirmation_interval, expiry_alert_thresholds,
    flap_detection_enabled, flap_threshold, flap_window_seconds, flap_max_duration_minutes,
    last_status_transition, flap_started_at, reminder_interval_minutes,
    heartbeat_slug, heartbeat_interval, heartbeat_grace, last_ping_at,
    keyword, keyword_mode, protocol_type, protocol_port,
    host_id
)
VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?
)
`

type CreateResourceParams struct {
	ID                      string         `json:"id"`
	CreatedAt               time.Time      `json:"created_at"`
	UpdatedAt               time.Time      `json:"updated_at"`
	Name                    string         `json:"name"`
	Type                    string         `json:"type"`
	Interval                int64          `json:"interval"`
	Timeout                 int64          `json:"timeout"`
	Target                  string         `json:"target"`
	LastChecked             sql.NullTime   `json:"last_checked"`
	Status                  string         `json:"status"`
	IsActive                int64          `json:"is_active"`
	FailureCount            int64          `json:"failure_count"`
	SslExpirationDate       sql.NullTime   `json:"ssl_expiration_date"`
	SslIssuer               sql.NullString `json:"ssl_issuer"`
	DomainExpirationDate    sql.NullTime   `json:"domain_expiration_date"`
	DomainRegistrar         sql.NullString `json:"domain_registrar"`
	ComponentID             sql.NullString `json:"component_id"`
	ConfirmationChecks      int64          `json:"confirmation_checks"`
	ConfirmationInterval    int64          `json:"confirmation_interval"`
	ExpiryAlertThresholds   sql.NullString `json:"expiry_alert_thresholds"`
	FlapDetectionEnabled    int64          `json:"flap_detection_enabled"`
	FlapThreshold           int64          `json:"flap_threshold"`
	FlapWindowSeconds       int64          `json:"flap_window_seconds"`
	FlapMaxDurationMinutes  int64          `json:"flap_max_duration_minutes"`
	LastStatusTransition    sql.NullTime   `json:"last_status_transition"`
	FlapStartedAt           sql.NullTime   `json:"flap_started_at"`
	ReminderIntervalMinutes int64          `json:"reminder_interval_minutes"`
	HeartbeatSlug           sql.NullString `json:"heartbeat_slug"`
	HeartbeatInterval       sql.NullInt64  `json:"heartbeat_interval"`
	HeartbeatGrace          sql.NullInt64  `json:"heartbeat_grace"`
	LastPingAt              sql.NullTime   `json:"last_ping_at"`
	Keyword                 sql.NullString `json:"keyword"`
	KeywordMode             sql.NullString `json:"keyword_mode"`
	ProtocolType            sql.NullString `json:"protocol_type"`
	ProtocolPort            sql.NullInt64  `json:"protocol_port"`
	HostID                  sql.NullString `json:"host_id"`
}

// PR1 of US1: CRUD without M2M and without 1-to-1 preloads.
// Mirror of postgres/resource.sql with SQLite-specific date math for
// FindMissedHeartbeats (strftime instead of EXTRACT EPOCH).
func (q *Queries) CreateResource(ctx context.Context, arg CreateResourceParams) error {
	_, err := q.db.ExecContext(ctx, createResource,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.Type,
		arg.Interval,
		arg.Timeout,
		arg.Target,
		arg.LastChecked,
		arg.Status,
		arg.IsActive,
		arg.FailureCount,
		arg.SslExpirationDate,
		arg.SslIssuer,
		arg.DomainExpirationDate,
		arg.DomainRegistrar,
		arg.ComponentID,
		arg.ConfirmationChecks,
		arg.ConfirmationInterval,
		arg.ExpiryAlertThresholds,
		arg.FlapDetectionEnabled,
		arg.FlapThreshold,
		arg.FlapWindowSeconds,
		arg.FlapMaxDurationMinutes,
		arg.LastStatusTransition,
		arg.FlapStartedAt,
		arg.ReminderIntervalMinutes,
		arg.HeartbeatSlug,
		arg.HeartbeatInterval,
		arg.HeartbeatGrace,
		arg.LastPingAt,
		arg.Keyword,
		arg.KeywordMode,
		arg.ProtocolType,
		arg.ProtocolPort,
		arg.HostID,
	)
	return err
}

const findMissedHeartbeatsSQLite = `-- name: FindMissedHeartbeatsSQLite :many
SELECT id, created_at, updated_at, name, type, interval, timeout, target, last_checked, status, is_active, failure_count, ssl_expiration_date, ssl_issuer, domain_expiration_date, domain_registrar, component_id, confirmation_checks, confirmation_interval, expiry_alert_thresholds, flap_detection_enabled, flap_threshold, flap_window_seconds, flap_max_duration_minutes, last_status_transition, flap_started_at, reminder_interval_minutes, heartbeat_slug, heartbeat_interval, heartbeat_grace, last_ping_at, keyword, keyword_mode, protocol_type, protocol_port, host_id FROM resources
WHERE type = 'heartbeat'
  AND status = 'up'
  AND is_active = 1
  AND last_ping_at IS NOT NULL
  AND (CAST(strftime('%s', substr(last_ping_at, 1, 19)) AS INTEGER) + heartbeat_interval + heartbeat_grace) < CAST(?1 AS INTEGER)
ORDER BY last_ping_at ASC
LIMIT CAST(?2 AS INTEGER)
`

type FindMissedHeartbeatsSQLiteParams struct {
	NowUnix  int64 `json:"now_unix"`
	RowLimit int64 `json:"row_limit"`
}

func (q *Queries) FindMissedHeartbeatsSQLite(ctx context.Context, arg FindMissedHeartbeatsSQLiteParams) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, findMissedHeartbeatsSQLite, arg.NowUnix, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Type,
			&i.Interval,
			&i.Timeout,
			&i.Target,
			&i.LastChecked,
			&i.Status,
			&i.IsActive,
			&i.FailureCount,
			&i.SslExpirationDate,
			&i.SslIssuer,
			&i.DomainExpirationDate,
			&i.DomainRegistrar,
			&i.ComponentID,
			&i.ConfirmationChecks,
			&i.ConfirmationInterval,
			&i.ExpiryAlertThresholds,
			&i.FlapDetectionEnabled,
			&i.FlapThreshold,
			&i.FlapWindowSeconds,
			&i.FlapMaxDurationMinutes,
			&i.LastStatusTransition,
			&i.FlapStartedAt,
			&i.ReminderIntervalMinutes,
			&i.HeartbeatSlug,
			&i.HeartbeatInterval,
			&i.HeartbeatGrace,
			&i.LastPingAt,
			&i.Keyword,
			&i.KeywordMode,
			&i.ProtocolType,
			&i.ProtocolPort,
			&i.HostID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findResourceByHeartbeatSlug = `-- name: FindResourceByHeartbeatSlug :one
SELECT id, created_at, updated_at, name, type, interval, timeout, target, last_checked, status, is_active, failure_count, ssl_expiration_date, ssl_issuer, domain_expiration_date, domain_registrar, component_id, confirmation_checks, confirmation_interval, expiry_alert_thresholds, flap_detection_enabled, flap_threshold, flap_window_seconds, flap_max_duration_minutes, last_status_transition, flap_started_at, reminder_interval_minutes, heartbeat_slug, heartbeat_interval, heartbeat_grace, last_ping_at, keyword, keyword_mode, protocol_type, protocol_port, host_id FROM resources
WHERE heartbeat_slug = ?
  AND type = 'heartbeat'
  AND is_active = 1
`

func (q *Queries) FindResourceByHeartbeatSlug(ctx context.Context, heartbeatSlug sql.NullString) (Resource, error) {
	row := q.db.QueryRowContext(ctx, findResourceByHeartbeatSlug, heartbeatSlug)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Type,
		&i.Interval,
		&i.Timeout,
		&i.Target,
		&i.LastChecked,
		&i.Status,
		&i.IsActive,
		&i.FailureCount,
		&i.SslExpirationDate,
		&i.SslIssuer,
		&i.DomainExpirationDate,
		&i.DomainRegistrar,
		&i.ComponentID,
		&i.ConfirmationChecks,
		&i.ConfirmationInterval,
		&i.ExpiryAlertThresholds,
		&i.FlapDetectionEnabled,
		&i.FlapThreshold,
		&i.FlapWindowSeconds,
		&i.FlapMaxDurationMinutes,
		&i.LastStatusTransition,
		&i.FlapStartedAt,
		&i.ReminderIntervalMinutes,
		&i.HeartbeatSlug,
		&i.HeartbeatInterval,
		&i.HeartbeatGrace,
		&i.LastPingAt,
		&i.Keyword,
		&i.KeywordMode,
		&i.ProtocolType,
		&i.ProtocolPort,
		&i.HostID,
	)
	return i, err
}

const findResourceByID = `-- name: FindResourceByID :one
SELECT id, created_at, updated_at, name, type, interval, timeout, target, last_checked, status, is_active, failure_count, ssl_expiration_date, ssl_issuer, domain_expiration_date, domain_registrar, component_id, confirmation_checks, confirmation_interval, expiry_alert_thresholds, flap_detection_enabled, flap_threshold, flap_window_seconds, flap_max_duration_minutes, last_status_transition, flap_started_at, reminder_interval_minutes, heartbeat_slug, heartbeat_interval, heartbeat_grace, last_ping_at, keyword, keyword_mode, protocol_type, protocol_port, host_id FROM resources WHERE id = ? AND is_active = 1
`

func (q *Queries) FindResourceByID(ctx context.Context, id string) (Resource, error) {
	row := q.db.QueryRowContext(ctx, findResourceByID, id)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Type,
		&i.Interval,
		&i.Timeout,
		&i.Target,
		&i.LastChecked,
		&i.Status,
		&i.IsActive,
		&i.FailureCount,
		&i.SslExpirationDate,
		&i.SslIssuer,
		&i.DomainExpirationDate,
		&i.DomainRegistrar,
		&i.ComponentID,
		&i.ConfirmationChecks,
		&i.ConfirmationInterval,
		&i.ExpiryAlertThresholds,
		&i.FlapDetectionEnabled,
		&i.FlapThreshold,
		&i.FlapWindowSeconds,
		&i.FlapMaxDurationMinutes,
		&i.LastStatusTransition,
		&i.FlapStartedAt,
		&i.ReminderIntervalMinutes,
		&i.HeartbeatSlug,
		&i.HeartbeatInterval,
		&i.HeartbeatGrace,
		&i.LastPingAt,
		&i.Keyword,
		&i.KeywordMode,
		&i.ProtocolType,
		&i.ProtocolPort,
		&i.HostID,
	)
	return i, err
}

const findResourceIDsByTagName = `-- name: FindResourceIDsByTagName :many
SELECT r.id
FROM resources r
JOIN resource_tags rt ON r.id = rt.resource_id
JOIN tags t ON rt.tag_id = t.id
WHERE t.name = ? AND r.is_active = 1
ORDER BY r.created_at DESC
LIMIT ? OFFSET ?
`

type FindResourceIDsByTagNameParams struct {
	Name   string `json:"name"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) FindResourceIDsByTagName(ctx context.Context, arg FindResourceIDsByTagNameParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, findResourceIDsByTagName, arg.Name, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findResourcesByComponentID = `-- name: FindResourcesByComponentID :many
SELECT id, created_at, updated_at, name, type, interval, timeout, target, last_checked, status, is_active, failure_count, ssl_expiration_date, ssl_issuer, domain_expiration_date, domain_registrar, component_id, confirmation_checks, confirmation_interval, expiry_alert_thresholds, flap_detection_enabled, flap_threshold, flap_window_seconds, flap_max_duration_minutes, last_status_transition, flap_started_at, reminder_interval_minutes, heartbeat_slug, heartbeat_interval, heartbeat_grace, last_ping_at, keyword, keyword_mode, protocol_type, protocol_port, host_id FROM resources
WHERE component_id = ? AND is_active = 1
ORDER BY created_at DESC
`

func (q *Queries) FindResourcesByComponentID(ctx context.Context, componentID sql.NullString) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, findResourcesByComponentID, componentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Type,
			&i.Interval,
			&i.Timeout,
			&i.Target,
			&i.LastChecked,
			&i.Status,
			&i.IsActive,
			&i.FailureCount,
			&i.SslExpirationDate,
			&i.SslIssuer,
			&i.DomainExpirationDate,
			&i.DomainRegistrar,
			&i.ComponentID,
			&i.ConfirmationChecks,
			&i.ConfirmationInterval,
			&i.ExpiryAlertThresholds,
			&i.FlapDetectionEnabled,
			&i.FlapThreshold,
			&i.FlapWindowSeconds,
			&i.FlapMaxDurationMinutes,
			&i.LastStatusTransition,
			&i.FlapStartedAt,
			&i.ReminderIntervalMinutes,
			&i.HeartbeatSlug,
			&i.HeartbeatInterval,
			&i.HeartbeatGrace,
			&i.LastPingAt,
			&i.Keyword,
			&i.KeywordMode,
			&i.ProtocolType,
			&i.ProtocolPort,
			&i.HostID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findResourcesByIDs = `-- name: FindResourcesByIDs :many
SELECT id, created_at, updated_at, name, type, interval, timeout, target, last_checked, status, is_active, failure_count, ssl_expiration_date, ssl_issuer, domain_expiration_date, domain_registrar, component_id, confirmation_checks, confirmation_interval, expiry_alert_thresholds, flap_detection_enabled, flap_threshold, flap_window_seconds, flap_max_duration_minutes, last_status_transition, flap_started_at, reminder_interval_minutes, heartbeat_slug, heartbeat_interval, heartbeat_grace, last_ping_at, keyword, keyword_mode, protocol_type, protocol_port, host_id FROM resources WHERE id IN (/*SLICE:ids*/?)
`

func (q *Queries) FindResourcesByIDs(ctx context.Context, ids []string) ([]Resource, error) {
	query := findResourcesByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Type,
			&i.Interval,
			&i.Timeout,
			&i.Target,
			&i.LastChecked,
			&i.Status,
			&i.IsActive,
			&i.FailureCount,
			&i.SslExpirationDate,
			&i.SslIssuer,
			&i.DomainExpirationDate,
			&i.DomainRegistrar,
			&i.ComponentID,
			&i.ConfirmationChecks,
			&i.ConfirmationInterval,
			&i.ExpiryAlertThresholds,
			&i.FlapDetectionEnabled,
			&i.FlapThreshold,
			&i.FlapWindowSeconds,
			&i.FlapMaxDurationMinutes,
			&i.LastStatusTransition,
			&i.FlapStartedAt,
			&i.ReminderIntervalMinutes,
			&i.HeartbeatSlug,
			&i.HeartbeatInterval,
			&i.HeartbeatGrace,
			&i.LastPingAt,
			&i.Keyword,
			&i.KeywordMode,
			&i.ProtocolType,
			&i.ProtocolPort,
			&i.HostID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkResourceChannel = `-- name: LinkResourceChannel :exec

INSERT INTO resource_notification_channels (resource_id, notification_channel_id)
VALUES (?, ?)
ON CONFLICT DO NOTHING
`

type LinkResourceChannelParams struct {
	ResourceID            string `json:"resource_id"`
	NotificationChannelID string `json:"notification_channel_id"`
}

// M2M: resource_notification_channels ---------------------------------------
func (q *Queries) LinkResourceChannel(ctx context.Context, arg LinkResourceChannelParams) error {
	_, err := q.db.ExecContext(ctx, linkResourceChannel, arg.ResourceID, arg.NotificationChannelID)
	return err
}

const linkResourceTag = `-- name: LinkResourceTag :exec

INSERT INTO resource_tags (resource_id, tag_id) VALUES (?, ?)
ON CONFLICT DO NOTHING
`

type LinkResourceTagParams struct {
	ResourceID string `json:"resource_id"`
	TagID      string `json:"tag_id"`
}

// M2M: resource_tags ---------------------------------------------------------
func (q *Queries) LinkResourceTag(ctx context.Context, arg LinkResourceTagParams) error {
	_, err := q.db.ExecContext(ctx, linkResourceTag, arg.ResourceID, arg.TagID)
	return err
}

const listActiveResources = `-- name: ListActiveResources :many
SELECT id, created_at, updated_at, name, type, interval, timeout, target, last_checked, status, is_active, failure_count, ssl_expiration_date, ssl_issuer, domain_expiration_date, domain_registrar, component_id, confirmation_checks, confirmation_interval, expiry_alert_thresholds, flap_detection_enabled, flap_threshold, flap_window_seconds, flap_max_duration_minutes, last_status_transition, flap_started_at, reminder_interval_minutes, heartbeat_slug, heartbeat_interval, heartbeat_grace, last_ping_at, keyword, keyword_mode, protocol_type, protocol_port, host_id FROM resources
WHERE is_active = 1
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListActiveResourcesParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListActiveResources(ctx context.Context, arg ListActiveResourcesParams) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listActiveResources, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Type,
			&i.Interval,
			&i.Timeout,
			&i.Target,
			&i.LastChecked,
			&i.Status,
			&i.IsActive,
			&i.FailureCount,
			&i.SslExpirationDate,
			&i.SslIssuer,
			&i.DomainExpirationDate,
			&i.DomainRegistrar,
			&i.ComponentID,
			&i.ConfirmationChecks,
			&i.ConfirmationInterval,
			&i.ExpiryAlertThresholds,
			&i.FlapDetectionEnabled,
			&i.FlapThreshold,
			&i.FlapWindowSeconds,
			&i.FlapMaxDurationMinutes,
			&i.LastStatusTransition,
			&i.FlapStartedAt,
			&i.ReminderIntervalMinutes,
			&i.HeartbeatSlug,
			&i.HeartbeatInterval,
			&i.HeartbeatGrace,
			&i.LastPingAt,
			&i.Keyword,
			&i.KeywordMode,
			&i.ProtocolType,
			&i.ProtocolPort,
			&i.HostID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelIDsByResourceID = `-- name: ListChannelIDsByResourceID :many
SELECT notification_channel_id FROM resource_notification_channels
WHERE resource_id = ?
`

func (q *Queries) ListChannelIDsByResourceID(ctx context.Context, resourceID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listChannelIDsByResourceID, resourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var notification_channel_id string
		if err := rows.Scan(&notification_channel_id); err != nil {
			return nil, err
		}
		items = append(items, notification_channel_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelsByResourceIDs = `-- name: ListChannelsByResourceIDs :many
SELECT rnc.resource_id,
       nc.id, nc.name, nc.type, nc.config, nc.enabled_by_default,
       nc.created_at, nc.updated_at
FROM resource_notification_channels rnc
JOIN notification_channels nc ON rnc.notification_channel_id = nc.id
WHERE rnc.resource_id IN (/*SLICE:resource_ids*/?)
`

type ListChannelsByResourceIDsRow struct {
	ResourceID       string    `json:"resource_id"`
	ID               string    `json:"id"`
	Name             string    `json:"name"`
	Type             string    `json:"type"`
	Config           []byte    `json:"config"`
	EnabledByDefault int64     `json:"enabled_by_default"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

func (q *Queries) ListChannelsByResourceIDs(ctx context.Context, resourceIds []string) ([]ListChannelsByResourceIDsRow, error) {
	query := listChannelsByResourceIDs
	var queryParams []interface{}
	if len(resourceIds) > 0 {
		for _, v := range resourceIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:resource_ids*/?", strings.Repeat(",?", len(resourceIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:resource_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChannelsByResourceIDsRow{}
	for rows.Next() {
		var i ListChannelsByResourceIDsRow
		if err := rows.Scan(
			&i.ResourceID,
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Config,
			&i.EnabledByDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComponentsByIDs = `-- name: ListComponentsByIDs :many

SELECT id, created_at, updated_at, name, description,
       last_notification_status, grouping_window_seconds
FROM components
WHERE id IN (/*SLICE:ids*/?)
`

// 1-to-1 preloads ------------------------------------------------------------
func (q *Queries) ListComponentsByIDs(ctx context.Context, ids []string) ([]Component, error) {
	query := listComponentsByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Component{}
	for rows.Next() {
		var i Component
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Description,
			&i.LastNotificationStatus,
			&i.GroupingWindowSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCredentialsByResourceIDs = `-- name: ListCredentialsByResourceIDs :many
SELECT id, resource_id, username, password, options, created_at, updated_at
FROM resource_credentials
WHERE resource_id IN (/*SLICE:resource_ids*/?)
`

func (q *Queries) ListCredentialsByResourceIDs(ctx context.Context, resourceIds []string) ([]ResourceCredential, error) {
	query := listCredentialsByResourceIDs
	var queryParams []interface{}
	if len(resourceIds) > 0 {
		for _, v := range resourceIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:resource_ids*/?", strings.Repeat(",?", len(resourceIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:resource_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResourceCredential{}
	for rows.Next() {
		var i ResourceCredential
		if err := rows.Scan(
			&i.ID,
			&i.ResourceID,
			&i.Username,
			&i.Password,
			&i.Options,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResources = `-- name: ListResources :many
SELECT id, created_at, updated_at, name, type, interval, timeout, target, last_checked, status, is_active, failure_count, ssl_expiration_date, ssl_issuer, domain_expiration_date, domain_registrar, component_id, confirmation_checks, confirmation_interval, expiry_alert_thresholds, flap_detection_enabled, flap_threshold, flap_window_seconds, flap_max_duration_minutes, last_status_transition, flap_started_at, reminder_interval_minutes, heartbeat_slug, heartbeat_interval, heartbeat_grace, last_ping_at, keyword, keyword_mode, protocol_type, protocol_port, host_id FROM resources
WHERE is_active = 1
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListResourcesParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListResources(ctx context.Context, arg ListResourcesParams) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listResources, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Type,
			&i.Interval,
			&i.Timeout,
			&i.Target,
			&i.LastChecked,
			&i.Status,
			&i.IsActive,
			&i.FailureCount,
			&i.SslExpirationDate,
			&i.SslIssuer,
			&i.DomainExpirationDate,
			&i.DomainRegistrar,
			&i.ComponentID,
			&i.ConfirmationChecks,
			&i.ConfirmationInterval,
			&i.ExpiryAlertThresholds,
			&i.FlapDetectionEnabled,
			&i.FlapThreshold,
			&i.FlapWindowSeconds,
			&i.FlapMaxDurationMinutes,
			&i.LastStatusTransition,
			&i.FlapStartedAt,
			&i.ReminderIntervalMinutes,
			&i.HeartbeatSlug,
			&i.HeartbeatInterval,
			&i.HeartbeatGrace,
			&i.LastPingAt,
			&i.Keyword,
			&i.KeywordMode,
			&i.ProtocolType,
			&i.ProtocolPort,
			&i.HostID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduledResources = `-- name: ListScheduledResources :many
SELECT id, created_at, updated_at, name, type, interval, timeout, target, last_checked, status, is_active, failure_count, ssl_expiration_date, ssl_issuer, domain_expiration_date, domain_registrar, component_id, confirmation_checks, confirmation_interval, expiry_alert_thresholds, flap_detection_enabled, flap_threshold, flap_window_seconds, flap_max_duration_minutes, last_status_transition, flap_started_at, reminder_interval_minutes, heartbeat_slug, heartbeat_interval, heartbeat_grace, last_ping_at, keyword, keyword_mode, protocol_type, protocol_port, host_id FROM resources
WHERE is_active = 1
ORDER BY id ASC
`

func (q *Queries) ListScheduledResources(ctx context.Context) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listScheduledResources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Type,
			&i.Interval,
			&i.Timeout,
			&i.Target,
			&i.LastChecked,
			&i.Status,
			&i.IsActive,
			&i.FailureCount,
			&i.SslExpirationDate,
			&i.SslIssuer,
			&i.DomainExpirationDate,
			&i.DomainRegistrar,
			&i.ComponentID,
			&i.ConfirmationChecks,
			&i.ConfirmationInterval,
			&i.ExpiryAlertThresholds,
			&i.FlapDetectionEnabled,
			&i.FlapThreshold,
			&i.FlapWindowSeconds,
			&i.FlapMaxDurationMinutes,
			&i.LastStatusTransition,
			&i.FlapStartedAt,
			&i.ReminderIntervalMinutes,
			&i.HeartbeatSlug,
			&i.HeartbeatInterval,
			&i.HeartbeatGrace,
			&i.LastPingAt,
			&i.Keyword,
			&i.KeywordMode,
			&i.ProtocolType,
			&i.ProtocolPort,
			&i.HostID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagIDsByResourceID = `-- name: ListTagIDsByResourceID :many
SELECT tag_id FROM resource_tags WHERE resource_id = ?
`

func (q *Queries) ListTagIDsByResourceID(ctx context.Context, resourceID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listTagIDsByResourceID, resourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var tag_id string
		if err := rows.Scan(&tag_id); err != nil {
			return nil, err
		}
		items = append(items, tag_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsByResourceIDs = `-- name: ListTagsByResourceIDs :many
SELECT rt.resource_id, t.id, t.name, t.color, t.description, t.created_at, t.updated_at
FROM resource_tags rt
JOIN tags t ON rt.tag_id = t.id
WHERE rt.resource_id IN (/*SLICE:resource_ids*/?)
`

type ListTagsByResourceIDsRow struct {
	ResourceID  string         `json:"resource_id"`
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Color       sql.NullString `json:"color"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

func (q *Queries) ListTagsByResourceIDs(ctx context.Context, resourceIds []string) ([]ListTagsByResourceIDsRow, error) {
	query := listTagsByResourceIDs
	var queryParams []interface{}
	if len(resourceIds) > 0 {
		for _, v := range resourceIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:resource_ids*/?", strings.Repeat(",?", len(resourceIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:resource_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTagsByResourceIDsRow{}
	for rows.Next() {
		var i ListTagsByResourceIDsRow
		if err := rows.Scan(
			&i.ResourceID,
			&i.ID,
			&i.Name,
			&i.Color,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setResourceHostID = `-- name: SetResourceHostID :execrows
UPDATE resources SET host_id = ?, updated_at = ? WHERE id = ?
`

type SetResourceHostIDParams struct {
	HostID    sql.NullString `json:"host_id"`
	UpdatedAt time.Time      `json:"updated_at"`
	ID        string         `json:"id"`
}

func (q *Queries) SetResourceHostID(ctx context.Context, arg SetResourceHostIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setResourceHostID, arg.HostID, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const softDeleteResource = `-- name: SoftDeleteResource :execrows
UPDATE resources SET is_active = 0
WHERE id = ? AND is_active = 1
`

func (q *Queries) SoftDeleteResource(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteResource, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const unlinkResourceChannel = `-- name: UnlinkResourceChannel :exec
DELETE FROM resource_notification_channels
WHERE resource_id = ? AND notification_channel_id = ?
`

type UnlinkResourceChannelParams struct {
	ResourceID            string `json:"resource_id"`
	NotificationChannelID string `json:"notification_channel_id"`
}

func (q *Queries) UnlinkResourceChannel(ctx context.Context, arg UnlinkResourceChannelParams) error {
	_, err := q.db.ExecContext(ctx, unlinkResourceChannel, arg.ResourceID, arg.NotificationChannelID)
	return err
}

const unlinkResourceTag = `-- name: UnlinkResourceTag :exec
DELETE FROM resource_tags WHERE resource_id = ? AND tag_id = ?
`

type UnlinkResourceTagParams struct {
	ResourceID string `json:"resource_id"`
	TagID      string `json:"tag_id"`
}

func (q *Queries) UnlinkResourceTag(ctx context.Context, arg UnlinkResourceTagParams) error {
	_, err := q.db.ExecContext(ctx, unlinkResourceTag, arg.ResourceID, arg.TagID)
	return err
}

const updateResourceLastPingAt = `-- name: UpdateResourceLastPingAt :execrows
UPDATE resources SET last_ping_at = ?2
WHERE id = ?1 AND type = 'heartbeat' AND is_active = 1
`

type UpdateResourceLastPingAtParams struct {
	ID         string       `json:"id"`
	LastPingAt sql.NullTime `json:"last_ping_at"`
}

func (q *Queries) UpdateResourceLastPingAt(ctx context.Context, arg UpdateResourceLastPingAtParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateResourceLastPingAt, arg.ID, arg.LastPingAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateResourceMain = `-- name: UpdateResourceMain :execrows
UPDATE resources
SET name                      = ?2,
    type                      = ?3,
    target                    = ?4,
    interval                  = ?5,
    timeout                   = ?6,
    is_active                 = ?7,
    confirmation_checks       = ?8,
    confirmation_interval     = ?9,
    component_id              = ?10,
    expiry_alert_thresholds   = ?11,
    flap_detection_enabled    = ?12,
    flap_threshold            = ?13,
    flap_window_seconds       = ?14,
    flap_max_duration_minutes = ?15,
    reminder_interval_minutes = ?16,
    heartbeat_interval        = ?17,
    heartbeat_grace           = ?18,
    updated_at                = ?19
WHERE id = ?1
`

type UpdateResourceMainParams struct {
	ID                      string         `json:"id"`
	Name                    string         `json:"name"`
	Type                    string         `json:"type"`
	Target                  string         `json:"target"`
	Interval                int64          `json:"interval"`
	Timeout                 int64          `json:"timeout"`
	IsActive                int64          `json:"is_active"`
	ConfirmationChecks      int64          `json:"confirmation_checks"`
	ConfirmationInterval    int64          `json:"confirmation_interval"`
	ComponentID             sql.NullString `json:"component_id"`
	ExpiryAlertThresholds   sql.NullString `json:"expiry_alert_thresholds"`
	FlapDetectionEnabled    int64          `json:"flap_detection_enabled"`
	FlapThreshold           int64          `json:"flap_threshold"`
	FlapWindowSeconds       int64          `json:"flap_window_seconds"`
	FlapMaxDurationMinutes  int64          `json:"flap_max_duration_minutes"`
	ReminderIntervalMinutes int64          `json:"reminder_interval_minutes"`
	HeartbeatInterval       sql.NullInt64  `json:"heartbeat_interval"`
	HeartbeatGrace          sql.NullInt64  `json:"heartbeat_grace"`
	UpdatedAt               time.Time      `json:"updated_at"`
}

func (q *Queries) UpdateResourceMain(ctx context.Context, arg UpdateResourceMainParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateResourceMain,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Target,
		arg.Interval,
		arg.Timeout,
		arg.IsActive,
		arg.ConfirmationChecks,
		arg.ConfirmationInterval,
		arg.ComponentID,
		arg.ExpiryAlertThresholds,
		arg.FlapDetectionEnabled,
		arg.FlapThreshold,
		arg.FlapWindowSeconds,
		arg.FlapMaxDurationMinutes,
		arg.ReminderIntervalMinutes,
		arg.HeartbeatInterval,
		arg.HeartbeatGrace,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateResourceStatus = `-- name: UpdateResourceStatus :execrows
UPDATE resources SET status = ?2 WHERE id = ?1
`

type UpdateResourceStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateResourceStatus(ctx context.Context, arg UpdateResourceStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateResourceStatus, arg.ID, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
