// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: component.sql

package pgsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createComponent = `-- name: CreateComponent :exec
INSERT INTO components (
    id, created_at, updated_at, name, description,
    last_notification_status, grouping_window_seconds
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateComponentParams struct {
	ID                     string             `json:"id"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	Name                   string             `json:"name"`
	Description            pgtype.Text        `json:"description"`
	LastNotificationStatus string             `json:"last_notification_status"`
	GroupingWindowSeconds  int32              `json:"grouping_window_seconds"`
}

func (q *Queries) CreateComponent(ctx context.Context, arg CreateComponentParams) error {
	_, err := q.db.Exec(ctx, createComponent,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.Description,
		arg.LastNotificationStatus,
		arg.GroupingWindowSeconds,
	)
	return err
}

const deleteComponent = `-- name: DeleteComponent :execrows
DELETE FROM components WHERE id = $1
`

func (q *Queries) DeleteComponent(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteComponent, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findComponentByID = `-- name: FindComponentByID :one
SELECT id, created_at, updated_at, name, description, last_notification_status, grouping_window_seconds FROM components WHERE id = $1
`

func (q *Queries) FindComponentByID(ctx context.Context, id string) (Component, error) {
	row := q.db.QueryRow(ctx, findComponentByID, id)
	var i Component
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Description,
		&i.LastNotificationStatus,
		&i.GroupingWindowSeconds,
	)
	return i, err
}

const listComponents = `-- name: ListComponents :many
SELECT id, created_at, updated_at, name, description, last_notification_status, grouping_window_seconds FROM components
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListComponentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListComponents(ctx context.Context, arg ListComponentsParams) ([]Component, error) {
	rows, err := q.db.Query(ctx, listComponents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Component{}
	for rows.Next() {
		var i Component
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Description,
			&i.LastNotificationStatus,
			&i.GroupingWindowSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesByComponentID = `-- name: ListResourcesByComponentID :many
SELECT id, created_at, updated_at, name, type, interval, timeout, target, last_checked, status, is_active, failure_count, ssl_expiration_date, ssl_issuer, domain_expiration_date, domain_registrar, component_id, confirmation_checks, confirmation_interval, expiry_alert_thresholds, flap_detection_enabled, flap_threshold, flap_window_seconds, flap_max_duration_minutes, last_status_transition, flap_started_at, reminder_interval_minutes, heartbeat_slug, heartbeat_interval, heartbeat_grace, last_ping_at, keyword, keyword_mode, protocol_type, protocol_port, host_id FROM resources WHERE component_id = $1 ORDER BY created_at
`

func (q *Queries) ListResourcesByComponentID(ctx context.Context, componentID pgtype.Text) ([]Resource, error) {
	rows, err := q.db.Query(ctx, listResourcesByComponentID, componentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Type,
			&i.Interval,
			&i.Timeout,
			&i.Target,
			&i.LastChecked,
			&i.Status,
			&i.IsActive,
			&i.FailureCount,
			&i.SslExpirationDate,
			&i.SslIssuer,
			&i.DomainExpirationDate,
			&i.DomainRegistrar,
			&i.ComponentID,
			&i.ConfirmationChecks,
			&i.ConfirmationInterval,
			&i.ExpiryAlertThresholds,
			&i.FlapDetectionEnabled,
			&i.FlapThreshold,
			&i.FlapWindowSeconds,
			&i.FlapMaxDurationMinutes,
			&i.LastStatusTransition,
			&i.FlapStartedAt,
			&i.ReminderIntervalMinutes,
			&i.HeartbeatSlug,
			&i.HeartbeatInterval,
			&i.HeartbeatGrace,
			&i.LastPingAt,
			&i.Keyword,
			&i.KeywordMode,
			&i.ProtocolType,
			&i.ProtocolPort,
			&i.HostID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateComponent = `-- name: UpdateComponent :exec
UPDATE components
SET name = $2,
    description = $3,
    updated_at = $4
WHERE id = $1
`

type UpdateComponentParams struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateComponent(ctx context.Context, arg UpdateComponentParams) error {
	_, err := q.db.Exec(ctx, updateComponent,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.UpdatedAt,
	)
	return err
}

const updateComponentLastNotificationStatus = `-- name: UpdateComponentLastNotificationStatus :execrows
UPDATE components
SET last_notification_status = $2
WHERE id = $1
`

type UpdateComponentLastNotificationStatusParams struct {
	ID                     string `json:"id"`
	LastNotificationStatus string `json:"last_notification_status"`
}

func (q *Queries) UpdateComponentLastNotificationStatus(ctx context.Context, arg UpdateComponentLastNotificationStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateComponentLastNotificationStatus, arg.ID, arg.LastNotificationStatus)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
