// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: host.sql

package pgsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countHosts = `-- name: CountHosts :one
SELECT COUNT(*) FROM hosts
`

func (q *Queries) CountHosts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countHosts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createHost = `-- name: CreateHost :exec
INSERT INTO hosts (
    id, created_at, updated_at, name, os, agent_version,
    last_seen_at, last_cpu_pct, last_mem_pct, last_disk_pct,
    last_net_in, last_net_out, last_disks
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
`

type CreateHostParams struct {
	ID           string             `json:"id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Name         string             `json:"name"`
	Os           pgtype.Text        `json:"os"`
	AgentVersion pgtype.Text        `json:"agent_version"`
	LastSeenAt   pgtype.Timestamptz `json:"last_seen_at"`
	LastCpuPct   pgtype.Float8      `json:"last_cpu_pct"`
	LastMemPct   pgtype.Float8      `json:"last_mem_pct"`
	LastDiskPct  pgtype.Float8      `json:"last_disk_pct"`
	LastNetIn    pgtype.Int8        `json:"last_net_in"`
	LastNetOut   pgtype.Int8        `json:"last_net_out"`
	LastDisks    []byte             `json:"last_disks"`
}

func (q *Queries) CreateHost(ctx context.Context, arg CreateHostParams) error {
	_, err := q.db.Exec(ctx, createHost,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.Os,
		arg.AgentVersion,
		arg.LastSeenAt,
		arg.LastCpuPct,
		arg.LastMemPct,
		arg.LastDiskPct,
		arg.LastNetIn,
		arg.LastNetOut,
		arg.LastDisks,
	)
	return err
}

const deleteHost = `-- name: DeleteHost :execrows
DELETE FROM hosts WHERE id = $1
`

func (q *Queries) DeleteHost(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteHost, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findHostByID = `-- name: FindHostByID :one
SELECT id, created_at, updated_at, name, os, agent_version, last_seen_at, last_cpu_pct, last_mem_pct, last_disk_pct, last_net_in, last_net_out, last_disks FROM hosts WHERE id = $1
`

func (q *Queries) FindHostByID(ctx context.Context, id string) (Host, error) {
	row := q.db.QueryRow(ctx, findHostByID, id)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Os,
		&i.AgentVersion,
		&i.LastSeenAt,
		&i.LastCpuPct,
		&i.LastMemPct,
		&i.LastDiskPct,
		&i.LastNetIn,
		&i.LastNetOut,
		&i.LastDisks,
	)
	return i, err
}

const listHosts = `-- name: ListHosts :many
SELECT id, created_at, updated_at, name, os, agent_version, last_seen_at, last_cpu_pct, last_mem_pct, last_disk_pct, last_net_in, last_net_out, last_disks FROM hosts
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListHostsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListHosts(ctx context.Context, arg ListHostsParams) ([]Host, error) {
	rows, err := q.db.Query(ctx, listHosts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Host{}
	for rows.Next() {
		var i Host
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Os,
			&i.AgentVersion,
			&i.LastSeenAt,
			&i.LastCpuPct,
			&i.LastMemPct,
			&i.LastDiskPct,
			&i.LastNetIn,
			&i.LastNetOut,
			&i.LastDisks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHostSnapshot = `-- name: UpdateHostSnapshot :execrows
UPDATE hosts
SET last_seen_at  = $2,
    last_cpu_pct  = $3,
    last_mem_pct  = $4,
    last_disk_pct = $5,
    last_net_in   = $6,
    last_net_out  = $7,
    last_disks    = $8,
    os            = COALESCE($9, os),
    agent_version = COALESCE($10, agent_version),
    updated_at    = $11
WHERE id = $1
`

type UpdateHostSnapshotParams struct {
	ID           string             `json:"id"`
	LastSeenAt   pgtype.Timestamptz `json:"last_seen_at"`
	LastCpuPct   pgtype.Float8      `json:"last_cpu_pct"`
	LastMemPct   pgtype.Float8      `json:"last_mem_pct"`
	LastDiskPct  pgtype.Float8      `json:"last_disk_pct"`
	LastNetIn    pgtype.Int8        `json:"last_net_in"`
	LastNetOut   pgtype.Int8        `json:"last_net_out"`
	LastDisks    []byte             `json:"last_disks"`
	Os           pgtype.Text        `json:"os"`
	AgentVersion pgtype.Text        `json:"agent_version"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateHostSnapshot(ctx context.Context, arg UpdateHostSnapshotParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateHostSnapshot,
		arg.ID,
		arg.LastSeenAt,
		arg.LastCpuPct,
		arg.LastMemPct,
		arg.LastDiskPct,
		arg.LastNetIn,
		arg.LastNetOut,
		arg.LastDisks,
		arg.Os,
		arg.AgentVersion,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
