// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: host_credential.sql

package pgsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createHostCredential = `-- name: CreateHostCredential :exec
INSERT INTO host_credentials (
    id, created_at, updated_at, host_id, hash, prefix, is_active, last_used_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateHostCredentialParams struct {
	ID         string             `json:"id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	HostID     string             `json:"host_id"`
	Hash       string             `json:"hash"`
	Prefix     string             `json:"prefix"`
	IsActive   bool               `json:"is_active"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
}

func (q *Queries) CreateHostCredential(ctx context.Context, arg CreateHostCredentialParams) error {
	_, err := q.db.Exec(ctx, createHostCredential,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.HostID,
		arg.Hash,
		arg.Prefix,
		arg.IsActive,
		arg.LastUsedAt,
	)
	return err
}

const deactivateAllHostCredentialsForHost = `-- name: DeactivateAllHostCredentialsForHost :exec
UPDATE host_credentials SET is_active = FALSE, updated_at = $2 WHERE host_id = $1 AND is_active = TRUE
`

type DeactivateAllHostCredentialsForHostParams struct {
	HostID    string             `json:"host_id"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) DeactivateAllHostCredentialsForHost(ctx context.Context, arg DeactivateAllHostCredentialsForHostParams) error {
	_, err := q.db.Exec(ctx, deactivateAllHostCredentialsForHost, arg.HostID, arg.UpdatedAt)
	return err
}

const deactivateHostCredentialByID = `-- name: DeactivateHostCredentialByID :execrows
UPDATE host_credentials SET is_active = FALSE, updated_at = $2 WHERE id = $1
`

type DeactivateHostCredentialByIDParams struct {
	ID        string             `json:"id"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) DeactivateHostCredentialByID(ctx context.Context, arg DeactivateHostCredentialByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, deactivateHostCredentialByID, arg.ID, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteHostCredentialsByHost = `-- name: DeleteHostCredentialsByHost :exec
DELETE FROM host_credentials WHERE host_id = $1
`

func (q *Queries) DeleteHostCredentialsByHost(ctx context.Context, hostID string) error {
	_, err := q.db.Exec(ctx, deleteHostCredentialsByHost, hostID)
	return err
}

const findActiveHostCredentialByHash = `-- name: FindActiveHostCredentialByHash :one
SELECT id, created_at, updated_at, host_id, hash, prefix, is_active, last_used_at FROM host_credentials
WHERE hash = $1 AND is_active = TRUE
`

func (q *Queries) FindActiveHostCredentialByHash(ctx context.Context, hash string) (HostCredential, error) {
	row := q.db.QueryRow(ctx, findActiveHostCredentialByHash, hash)
	var i HostCredential
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HostID,
		&i.Hash,
		&i.Prefix,
		&i.IsActive,
		&i.LastUsedAt,
	)
	return i, err
}

const listHostCredentialsByHost = `-- name: ListHostCredentialsByHost :many
SELECT id, created_at, updated_at, host_id, hash, prefix, is_active, last_used_at FROM host_credentials
WHERE host_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListHostCredentialsByHost(ctx context.Context, hostID string) ([]HostCredential, error) {
	rows, err := q.db.Query(ctx, listHostCredentialsByHost, hostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HostCredential{}
	for rows.Next() {
		var i HostCredential
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HostID,
			&i.Hash,
			&i.Prefix,
			&i.IsActive,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchHostCredentialLastUsed = `-- name: TouchHostCredentialLastUsed :exec
UPDATE host_credentials SET last_used_at = $2 WHERE id = $1
`

type TouchHostCredentialLastUsedParams struct {
	ID         string             `json:"id"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
}

func (q *Queries) TouchHostCredentialLastUsed(ctx context.Context, arg TouchHostCredentialLastUsedParams) error {
	_, err := q.db.Exec(ctx, touchHostCredentialLastUsed, arg.ID, arg.LastUsedAt)
	return err
}
