// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: host_alert_state.sql

package pgsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getHostAlertState = `-- name: GetHostAlertState :one
SELECT host_id, state, offline_since, alerted, updated_at
FROM host_alert_state
WHERE host_id = $1
`

func (q *Queries) GetHostAlertState(ctx context.Context, hostID string) (HostAlertState, error) {
	row := q.db.QueryRow(ctx, getHostAlertState, hostID)
	var i HostAlertState
	err := row.Scan(
		&i.HostID,
		&i.State,
		&i.OfflineSince,
		&i.Alerted,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertHostAlertState = `-- name: UpsertHostAlertState :exec
INSERT INTO host_alert_state (host_id, state, offline_since, alerted, updated_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (host_id) DO UPDATE SET
    state = EXCLUDED.state,
    offline_since = EXCLUDED.offline_since,
    alerted = EXCLUDED.alerted,
    updated_at = EXCLUDED.updated_at
`

type UpsertHostAlertStateParams struct {
	HostID       string             `json:"host_id"`
	State        string             `json:"state"`
	OfflineSince pgtype.Timestamptz `json:"offline_since"`
	Alerted      bool               `json:"alerted"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertHostAlertState(ctx context.Context, arg UpsertHostAlertStateParams) error {
	_, err := q.db.Exec(ctx, upsertHostAlertState,
		arg.HostID,
		arg.State,
		arg.OfflineSince,
		arg.Alerted,
		arg.UpdatedAt,
	)
	return err
}
