// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pgsqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Announcement struct {
	ID          string             `json:"id"`
	Severity    string             `json:"severity"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Dismissible bool               `json:"dismissible"`
	Active      bool               `json:"active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ApiKey struct {
	ID         string             `json:"id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	UserID     string             `json:"user_id"`
	Name       string             `json:"name"`
	KeyHash    string             `json:"key_hash"`
	KeyPrefix  string             `json:"key_prefix"`
	Scope      string             `json:"scope"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	LastUsedIp string             `json:"last_used_ip"`
	IsActive   bool               `json:"is_active"`
}

type Component struct {
	ID                     string             `json:"id"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	Name                   string             `json:"name"`
	Description            pgtype.Text        `json:"description"`
	LastNotificationStatus string             `json:"last_notification_status"`
	GroupingWindowSeconds  int32              `json:"grouping_window_seconds"`
}

type ComponentNotificationChannel struct {
	ComponentID           string `json:"component_id"`
	NotificationChannelID string `json:"notification_channel_id"`
}

type Dashboard struct {
	ID               string             `json:"id"`
	OwnerID          string             `json:"owner_id"`
	Name             string             `json:"name"`
	Scope            []byte             `json:"scope"`
	Widgets          []byte             `json:"widgets"`
	DefaultTimeRange string             `json:"default_time_range"`
	RefreshInterval  string             `json:"refresh_interval"`
	Visibility       string             `json:"visibility"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type EscalationPolicy struct {
	ID         string             `json:"id"`
	Name       string             `json:"name"`
	ScopeKind  string             `json:"scope_kind"`
	ScopeValue string             `json:"scope_value"`
	IsActive   bool               `json:"is_active"`
	Priority   int32              `json:"priority"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type EscalationStep struct {
	ID           string `json:"id"`
	PolicyID     string `json:"policy_id"`
	StepOrder    int32  `json:"step_order"`
	DelayMinutes int32  `json:"delay_minutes"`
	ChannelIds   []byte `json:"channel_ids"`
}

type ExpiryNotificationLog struct {
	ID         string             `json:"id"`
	ResourceID string             `json:"resource_id"`
	ExpiryType string             `json:"expiry_type"`
	Threshold  int32              `json:"threshold"`
	SentAt     pgtype.Timestamptz `json:"sent_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Host struct {
	ID           string             `json:"id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Name         string             `json:"name"`
	Os           pgtype.Text        `json:"os"`
	AgentVersion pgtype.Text        `json:"agent_version"`
	LastSeenAt   pgtype.Timestamptz `json:"last_seen_at"`
	LastCpuPct   pgtype.Float8      `json:"last_cpu_pct"`
	LastMemPct   pgtype.Float8      `json:"last_mem_pct"`
	LastDiskPct  pgtype.Float8      `json:"last_disk_pct"`
	LastNetIn    pgtype.Int8        `json:"last_net_in"`
	LastNetOut   pgtype.Int8        `json:"last_net_out"`
	LastDisks    []byte             `json:"last_disks"`
}

type HostAlertState struct {
	HostID       string             `json:"host_id"`
	State        string             `json:"state"`
	OfflineSince pgtype.Timestamptz `json:"offline_since"`
	Alerted      bool               `json:"alerted"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type HostCredential struct {
	ID         string             `json:"id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	HostID     string             `json:"host_id"`
	Hash       string             `json:"hash"`
	Prefix     string             `json:"prefix"`
	IsActive   bool               `json:"is_active"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
}

type HostMetric struct {
	ID        string             `json:"id"`
	HostID    string             `json:"host_id"`
	SampledAt pgtype.Timestamptz `json:"sampled_at"`
	CpuPct    float64            `json:"cpu_pct"`
	MemPct    float64            `json:"mem_pct"`
	NetIn     int64              `json:"net_in"`
	NetOut    int64              `json:"net_out"`
	Disks     []byte             `json:"disks"`
}

type Incident struct {
	ID         string             `json:"id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	ResourceID string             `json:"resource_id"`
	Cause      string             `json:"cause"`
	ResolvedAt pgtype.Timestamptz `json:"resolved_at"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	Details    []byte             `json:"details"`
}

type IncidentDiagnostic struct {
	ID                string             `json:"id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	IncidentID        string             `json:"incident_id"`
	RequestMethod     string             `json:"request_method"`
	RequestUrl        string             `json:"request_url"`
	RequestHeaders    string             `json:"request_headers"`
	RequestTimeout    int32              `json:"request_timeout"`
	HttpStatusCode    int32              `json:"http_status_code"`
	ResponseHeaders   string             `json:"response_headers"`
	ResponseBody      string             `json:"response_body"`
	ResponseSize      int32              `json:"response_size"`
	FailureType       string             `json:"failure_type"`
	ErrorMessage      string             `json:"error_message"`
	ErrorSummary      string             `json:"error_summary"`
	TotalDuration     int32              `json:"total_duration"`
	DnsDuration       int32              `json:"dns_duration"`
	TlsDuration       int32              `json:"tls_duration"`
	FirstByteDuration int32              `json:"first_byte_duration"`
	BodyTruncated     bool               `json:"body_truncated"`
	BodyEncoded       bool               `json:"body_encoded"`
	IcmpAvailable     pgtype.Bool        `json:"icmp_available"`
	IcmpReachable     pgtype.Bool        `json:"icmp_reachable"`
	IcmpRttMs         pgtype.Int4        `json:"icmp_rtt_ms"`
	RootCauseHint     string             `json:"root_cause_hint"`
	Keyword           pgtype.Text        `json:"keyword"`
	KeywordMode       pgtype.Text        `json:"keyword_mode"`
	KeywordFound      pgtype.Bool        `json:"keyword_found"`
}

type IncidentEventStep struct {
	ID         string             `json:"id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	IncidentID string             `json:"incident_id"`
	Step       string             `json:"step"`
	Message    pgtype.Text        `json:"message"`
}

type IncidentUpdate struct {
	ID         string             `json:"id"`
	IncidentID string             `json:"incident_id"`
	Status     string             `json:"status"`
	Message    string             `json:"message"`
	PostedBy   string             `json:"posted_by"`
	PostedAt   pgtype.Timestamptz `json:"posted_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Maintenance struct {
	ID             string             `json:"id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Title          string             `json:"title"`
	Description    pgtype.Text        `json:"description"`
	Strategy       string             `json:"strategy"`
	Status         string             `json:"status"`
	StartAt        pgtype.Timestamptz `json:"start_at"`
	EndAt          pgtype.Timestamptz `json:"end_at"`
	CronExpr       pgtype.Text        `json:"cron_expr"`
	WindowMinutes  pgtype.Int4        `json:"window_minutes"`
	Timezone       pgtype.Text        `json:"timezone"`
	EffectiveFrom  pgtype.Timestamptz `json:"effective_from"`
	EffectiveUntil pgtype.Timestamptz `json:"effective_until"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	EndedAt        pgtype.Timestamptz `json:"ended_at"`
}

type MaintenanceResource struct {
	MaintenanceID string `json:"maintenance_id"`
	ResourceID    string `json:"resource_id"`
}

type MonitoringActivity struct {
	ID            string             `json:"id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	ResourceID    string             `json:"resource_id"`
	Message       string             `json:"message"`
	Success       bool               `json:"success"`
	ResponseTime  int32              `json:"response_time"`
	ResponseData  []byte             `json:"response_data"`
	IsMaintenance bool               `json:"is_maintenance"`
}

type Notification struct {
	ID          string             `json:"id"`
	UserID      pgtype.Text        `json:"user_id"`
	Category    string             `json:"category"`
	Severity    string             `json:"severity"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	DeepLink    pgtype.Text        `json:"deep_link"`
	Payload     []byte             `json:"payload"`
	OccurredAt  pgtype.Timestamptz `json:"occurred_at"`
	ReadAt      pgtype.Timestamptz `json:"read_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type NotificationChannel struct {
	ID               string             `json:"id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	Name             string             `json:"name"`
	Type             string             `json:"type"`
	Config           []byte             `json:"config"`
	EnabledByDefault bool               `json:"enabled_by_default"`
	LastSentAt       pgtype.Timestamptz `json:"last_sent_at"`
	LastFailureAt    pgtype.Timestamptz `json:"last_failure_at"`
	Failures24h      int32              `json:"failures_24h"`
}

type NotificationEscalationState struct {
	ID                  string             `json:"id"`
	LastDigestAt        pgtype.Timestamptz `json:"last_digest_at"`
	WatermarkOccurredAt pgtype.Timestamptz `json:"watermark_occurred_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type NotificationEvent struct {
	ID          string             `json:"id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	IncidentID  string             `json:"incident_id"`
	Type        string             `json:"type"`
	Status      string             `json:"status"`
	ClaimOwner  pgtype.Text        `json:"claim_owner"`
	ClaimedAt   pgtype.Timestamptz `json:"claimed_at"`
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
	LastError   string             `json:"last_error"`
}

type ReportHistory struct {
	ID                string             `json:"id"`
	Period            string             `json:"period"`
	SentAt            pgtype.Timestamptz `json:"sent_at"`
	Status            string             `json:"status"`
	UptimePct         float64            `json:"uptime_pct"`
	IncidentCount     int32              `json:"incident_count"`
	DowntimeSeconds   int64              `json:"downtime_seconds"`
	RecipientEmail    string             `json:"recipient_email"`
	ResourceBreakdown []byte             `json:"resource_breakdown"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type ReportSetting struct {
	ID             string             `json:"id"`
	Enabled        bool               `json:"enabled"`
	RecipientEmail string             `json:"recipient_email"`
	Schedule       string             `json:"schedule"`
	Scope          string             `json:"scope"`
	LastSentAt     pgtype.Timestamptz `json:"last_sent_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Resource struct {
	ID                      string             `json:"id"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	Name                    string             `json:"name"`
	Type                    string             `json:"type"`
	Interval                int32              `json:"interval"`
	Timeout                 int32              `json:"timeout"`
	Target                  string             `json:"target"`
	LastChecked             pgtype.Timestamptz `json:"last_checked"`
	Status                  string             `json:"status"`
	IsActive                bool               `json:"is_active"`
	FailureCount            int32              `json:"failure_count"`
	SslExpirationDate       pgtype.Timestamptz `json:"ssl_expiration_date"`
	SslIssuer               pgtype.Text        `json:"ssl_issuer"`
	DomainExpirationDate    pgtype.Timestamptz `json:"domain_expiration_date"`
	DomainRegistrar         pgtype.Text        `json:"domain_registrar"`
	ComponentID             pgtype.Text        `json:"component_id"`
	ConfirmationChecks      int32              `json:"confirmation_checks"`
	ConfirmationInterval    int32              `json:"confirmation_interval"`
	ExpiryAlertThresholds   pgtype.Text        `json:"expiry_alert_thresholds"`
	FlapDetectionEnabled    bool               `json:"flap_detection_enabled"`
	FlapThreshold           int32              `json:"flap_threshold"`
	FlapWindowSeconds       int32              `json:"flap_window_seconds"`
	FlapMaxDurationMinutes  int32              `json:"flap_max_duration_minutes"`
	LastStatusTransition    pgtype.Timestamptz `json:"last_status_transition"`
	FlapStartedAt           pgtype.Timestamptz `json:"flap_started_at"`
	ReminderIntervalMinutes int32              `json:"reminder_interval_minutes"`
	HeartbeatSlug           pgtype.Text        `json:"heartbeat_slug"`
	HeartbeatInterval       pgtype.Int4        `json:"heartbeat_interval"`
	HeartbeatGrace          pgtype.Int4        `json:"heartbeat_grace"`
	LastPingAt              pgtype.Timestamp   `json:"last_ping_at"`
	Keyword                 pgtype.Text        `json:"keyword"`
	KeywordMode             pgtype.Text        `json:"keyword_mode"`
	ProtocolType            pgtype.Text        `json:"protocol_type"`
	ProtocolPort            pgtype.Int4        `json:"protocol_port"`
	HostID                  pgtype.Text        `json:"host_id"`
}

type ResourceCredential struct {
	ID         string             `json:"id"`
	ResourceID string             `json:"resource_id"`
	Username   pgtype.Text        `json:"username"`
	Password   []byte             `json:"password"`
	Options    []byte             `json:"options"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type ResourceNotificationChannel struct {
	ResourceID            string `json:"resource_id"`
	NotificationChannelID string `json:"notification_channel_id"`
}

type ResourceTag struct {
	ResourceID string `json:"resource_id"`
	TagID      string `json:"tag_id"`
}

type SchemaMigration struct {
	Version   string             `json:"version"`
	Name      string             `json:"name"`
	AppliedAt pgtype.Timestamptz `json:"applied_at"`
}

type Session struct {
	ID           string             `json:"id"`
	UserID       string             `json:"user_id"`
	Browser      string             `json:"browser"`
	Os           string             `json:"os"`
	Ip           string             `json:"ip"`
	Location     pgtype.Text        `json:"location"`
	LastActiveAt pgtype.Timestamptz `json:"last_active_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	RevokedAt    pgtype.Timestamptz `json:"revoked_at"`
}

type StatusPageSetting struct {
	ID                     string             `json:"id"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	Name                   string             `json:"name"`
	HomepageUrl            string             `json:"homepage_url"`
	CustomDomain           string             `json:"custom_domain"`
	GoogleAnalyticsID      string             `json:"google_analytics_id"`
	EnableDetailsPage      bool               `json:"enable_details_page"`
	ShowUptimePercentage   bool               `json:"show_uptime_percentage"`
	HidePausedMonitors     bool               `json:"hide_paused_monitors"`
	ShowIncidentHistory    bool               `json:"show_incident_history"`
	CustomDomainStatus     string             `json:"custom_domain_status"`
	CustomDomainSslStatus  string             `json:"custom_domain_ssl_status"`
	CustomDomainDnsRecords []byte             `json:"custom_domain_dns_records"`
	LogoUrlLight           string             `json:"logo_url_light"`
	LogoUrlDark            string             `json:"logo_url_dark"`
	FaviconUrl             string             `json:"favicon_url"`
	PrimaryColor           string             `json:"primary_color"`
	ThemeOverrides         []byte             `json:"theme_overrides"`
	UmamiWebsiteID         string             `json:"umami_website_id"`
	UmamiScriptUrl         string             `json:"umami_script_url"`
}

type Tag struct {
	ID          string             `json:"id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Name        string             `json:"name"`
	Color       pgtype.Text        `json:"color"`
	Description pgtype.Text        `json:"description"`
}

type TwoFactorResetToken struct {
	TokenHash string             `json:"token_hash"`
	UserID    string             `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type UptimeDailyAgg struct {
	ResourceID  string             `json:"resource_id"`
	Day         pgtype.Date        `json:"day"`
	Samples     int32              `json:"samples"`
	Up          int32              `json:"up"`
	Degraded    int32              `json:"degraded"`
	Down        int32              `json:"down"`
	UptimeRatio pgtype.Numeric     `json:"uptime_ratio"`
	ComputedAt  pgtype.Timestamptz `json:"computed_at"`
}

type User struct {
	ID                   string             `json:"id"`
	Email                string             `json:"email"`
	Name                 string             `json:"name"`
	HashedPassword       string             `json:"hashed_password"`
	PasswordInitialized  bool               `json:"password_initialized"`
	ForcePasswordChange  bool               `json:"force_password_change"`
	TwoFactorEnabled     bool               `json:"two_factor_enabled"`
	TwoFactorSecret      string             `json:"two_factor_secret"`
	TwoFactorBackupCodes []byte             `json:"two_factor_backup_codes"`
	LastLoginAt          pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}
