// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification_escalation_state.sql

package pgsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getNotificationEscalationState = `-- name: GetNotificationEscalationState :one
SELECT id, last_digest_at, watermark_occurred_at, updated_at
FROM notification_escalation_state
WHERE id = $1
`

func (q *Queries) GetNotificationEscalationState(ctx context.Context, id string) (NotificationEscalationState, error) {
	row := q.db.QueryRow(ctx, getNotificationEscalationState, id)
	var i NotificationEscalationState
	err := row.Scan(
		&i.ID,
		&i.LastDigestAt,
		&i.WatermarkOccurredAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertNotificationEscalationState = `-- name: UpsertNotificationEscalationState :exec
INSERT INTO notification_escalation_state (id, last_digest_at, watermark_occurred_at, updated_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE SET
    last_digest_at = EXCLUDED.last_digest_at,
    watermark_occurred_at = EXCLUDED.watermark_occurred_at,
    updated_at = EXCLUDED.updated_at
`

type UpsertNotificationEscalationStateParams struct {
	ID                  string             `json:"id"`
	LastDigestAt        pgtype.Timestamptz `json:"last_digest_at"`
	WatermarkOccurredAt pgtype.Timestamptz `json:"watermark_occurred_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertNotificationEscalationState(ctx context.Context, arg UpsertNotificationEscalationStateParams) error {
	_, err := q.db.Exec(ctx, upsertNotificationEscalationState,
		arg.ID,
		arg.LastDigestAt,
		arg.WatermarkOccurredAt,
		arg.UpdatedAt,
	)
	return err
}
