// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pgsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AvgResponseTimeByResourceInWindow(ctx context.Context, arg AvgResponseTimeByResourceInWindowParams) (float64, error)
	// One round-trip bulk avg grouped by resource. Used by the list path to
	// enrich each resource with its avg response time over a sliding window (30d).
	AvgResponseTimeByResourcesSince(ctx context.Context, arg AvgResponseTimeByResourcesSinceParams) ([]AvgResponseTimeByResourcesSinceRow, error)
	ClaimNotificationEventForUpdate(ctx context.Context, id string) (string, error)
	ClearResourceHostIDByHost(ctx context.Context, hostID pgtype.Text) error
	CountAPIKeysByUserID(ctx context.Context, userID string) (int64, error)
	CountExpiryNotificationLogsByKey(ctx context.Context, arg CountExpiryNotificationLogsByKeyParams) (int64, error)
	CountHosts(ctx context.Context) (int64, error)
	CountIncidentsByResourceID(ctx context.Context, resourceID string) (int64, error)
	// One round-trip count grouped by resource. Used by the list path to enrich
	// each resource with its incident count over a sliding window (e.g. 30d).
	CountIncidentsPerResourceSince(ctx context.Context, arg CountIncidentsPerResourceSinceParams) ([]CountIncidentsPerResourceSinceRow, error)
	CountMonitoringActivityByResourceSuccess(ctx context.Context, arg CountMonitoringActivityByResourceSuccessParams) (int64, error)
	CountMonitoringActivityByResourceTotal(ctx context.Context, arg CountMonitoringActivityByResourceTotalParams) (int64, error)
	CountMonitoringActivitySinceSuccess(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error)
	CountMonitoringActivitySinceTotal(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error)
	CountNotificationsForUser(ctx context.Context, arg CountNotificationsForUserParams) (int64, error)
	CountRecentTwoFactorResetTokensByUser(ctx context.Context, arg CountRecentTwoFactorResetTokensByUserParams) (int64, error)
	CountResourcesByComponentID(ctx context.Context, componentID pgtype.Text) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) error
	CreateAnnouncement(ctx context.Context, arg CreateAnnouncementParams) (Announcement, error)
	CreateComponent(ctx context.Context, arg CreateComponentParams) error
	CreateDashboard(ctx context.Context, arg CreateDashboardParams) (Dashboard, error)
	CreateEscalationPolicy(ctx context.Context, arg CreateEscalationPolicyParams) error
	CreateEscalationStep(ctx context.Context, arg CreateEscalationStepParams) error
	CreateExpiryNotificationLog(ctx context.Context, arg CreateExpiryNotificationLogParams) error
	CreateHost(ctx context.Context, arg CreateHostParams) error
	CreateHostCredential(ctx context.Context, arg CreateHostCredentialParams) error
	// US2 of spec 048: incident_repository sqlc migration. No M2M;
	// controlled-N+1 preload for Resource and IncidentDiagnostics
	// (1-to-1, FK uniqueIndex on incident_id).
	CreateIncident(ctx context.Context, arg CreateIncidentParams) error
	CreateIncidentDiagnostics(ctx context.Context, arg CreateIncidentDiagnosticsParams) (IncidentDiagnostic, error)
	CreateIncidentEventStep(ctx context.Context, arg CreateIncidentEventStepParams) error
	CreateIncidentUpdate(ctx context.Context, arg CreateIncidentUpdateParams) error
	CreateMaintenance(ctx context.Context, arg CreateMaintenanceParams) error
	CreateMonitoringActivity(ctx context.Context, arg CreateMonitoringActivityParams) error
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreateNotificationChannel(ctx context.Context, arg CreateNotificationChannelParams) error
	CreateNotificationEvent(ctx context.Context, arg CreateNotificationEventParams) error
	CreateReportHistory(ctx context.Context, arg CreateReportHistoryParams) (ReportHistory, error)
	// PR1 of US1: CRUD without M2M and without 1-to-1 preloads.
	// Deferred to later PRs: FindByTag (M2M JOIN), dynamic UpdateMonitoringState /
	// UpdateMetadata, Tags / NotificationChannels / Component / Credential preloads.
	CreateResource(ctx context.Context, arg CreateResourceParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateStatusPageSettings(ctx context.Context, arg CreateStatusPageSettingsParams) error
	CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error)
	CreateTwoFactorResetToken(ctx context.Context, arg CreateTwoFactorResetTokenParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeactivateAllHostCredentialsForHost(ctx context.Context, arg DeactivateAllHostCredentialsForHostParams) error
	DeactivateHostCredentialByID(ctx context.Context, arg DeactivateHostCredentialByIDParams) (int64, error)
	// Keep at most one sample per (host, minute) for rows older than the cutoff,
	// deleting the rest. MIN(id) is the earliest ULID in each minute bucket.
	DecimateHostMetrics(ctx context.Context, sampledAt pgtype.Timestamptz) (int64, error)
	DeleteAnnouncement(ctx context.Context, id string) (int64, error)
	DeleteComponent(ctx context.Context, id string) (int64, error)
	DeleteDashboard(ctx context.Context, id string) (int64, error)
	DeleteEscalationPolicy(ctx context.Context, id string) (int64, error)
	DeleteEscalationStepsByPolicy(ctx context.Context, policyID string) error
	DeleteExpiredTwoFactorResetTokens(ctx context.Context, expiresAt pgtype.Timestamptz) error
	DeleteExpiryNotificationLogsByResourceIDAndType(ctx context.Context, arg DeleteExpiryNotificationLogsByResourceIDAndTypeParams) error
	DeleteExpiryNotificationLogsOlderThan(ctx context.Context, sentAt pgtype.Timestamptz) error
	DeleteHost(ctx context.Context, id string) (int64, error)
	DeleteHostCredentialsByHost(ctx context.Context, hostID string) error
	DeleteHostMetricsByHost(ctx context.Context, hostID string) error
	DeleteHostMetricsOlderThan(ctx context.Context, sampledAt pgtype.Timestamptz) (int64, error)
	DeleteIncident(ctx context.Context, id string) (int64, error)
	DeleteIncidentDiagnostics(ctx context.Context, id string) (int64, error)
	DeleteIncidentEventStep(ctx context.Context, id string) (int64, error)
	DeleteIncidentUpdate(ctx context.Context, id string) error
	DeleteMaintenance(ctx context.Context, id string) (int64, error)
	DeleteNotificationChannel(ctx context.Context, id string) (int64, error)
	DeleteNotificationEvent(ctx context.Context, id string) error
	DeleteNotificationsOlderThan(ctx context.Context, cutoff pgtype.Timestamptz) (int64, error)
	DeleteResourceCredentialByResourceID(ctx context.Context, resourceID string) (int64, error)
	DeleteTag(ctx context.Context, id string) (int64, error)
	DeleteUser(ctx context.Context, id string) error
	FindAPIKeyByIDForUser(ctx context.Context, arg FindAPIKeyByIDForUserParams) (ApiKey, error)
	FindAPIKeyByKeyHash(ctx context.Context, keyHash string) (ApiKey, error)
	FindActiveHostCredentialByHash(ctx context.Context, hash string) (HostCredential, error)
	FindActiveIncidentByResourceID(ctx context.Context, resourceID string) (Incident, error)
	FindActiveMaintenancesForResource(ctx context.Context, arg FindActiveMaintenancesForResourceParams) ([]Maintenance, error)
	FindActiveTwoFactorResetToken(ctx context.Context, arg FindActiveTwoFactorResetTokenParams) (TwoFactorResetToken, error)
	FindComponentByID(ctx context.Context, id string) (Component, error)
	FindDashboardByID(ctx context.Context, id string) (FindDashboardByIDRow, error)
	FindDefaultNotificationChannels(ctx context.Context) ([]NotificationChannel, error)
	FindEarliestUptimeDailyAggDay(ctx context.Context) (interface{}, error)
	FindEscalationPolicyByID(ctx context.Context, id string) (EscalationPolicy, error)
	FindHostByID(ctx context.Context, id string) (Host, error)
	FindIncidentByID(ctx context.Context, id string) (Incident, error)
	FindIncidentDiagnosticsByIncidentID(ctx context.Context, incidentID string) (IncidentDiagnostic, error)
	// Single JOIN preload (Clarification Q1) — incident embedded into event step.
	FindIncidentEventStepByID(ctx context.Context, id string) (FindIncidentEventStepByIDRow, error)
	FindIncidentsByIDs(ctx context.Context, dollar_1 []string) ([]Incident, error)
	FindIncidentsByResource(ctx context.Context, arg FindIncidentsByResourceParams) ([]Incident, error)
	FindLastIncidentEventStepByIncidentAndStep(ctx context.Context, arg FindLastIncidentEventStepByIncidentAndStepParams) (IncidentEventStep, error)
	FindLastResolvedIncident(ctx context.Context) (Incident, error)
	FindMaintenanceByID(ctx context.Context, id string) (Maintenance, error)
	FindMissedHeartbeatsPG(ctx context.Context, arg FindMissedHeartbeatsPGParams) ([]Resource, error)
	FindMonitoringActivitiesByResourceID(ctx context.Context, arg FindMonitoringActivitiesByResourceIDParams) ([]MonitoringActivity, error)
	FindNotificationChannelByID(ctx context.Context, id string) (NotificationChannel, error)
	FindNotificationChannelsByComponentID(ctx context.Context, componentID string) ([]NotificationChannel, error)
	FindNotificationChannelsByResourceID(ctx context.Context, resourceID string) ([]NotificationChannel, error)
	FindNotificationChannelsByType(ctx context.Context, type_ string) ([]NotificationChannel, error)
	FindNotificationEventByID(ctx context.Context, id string) (NotificationEvent, error)
	FindPendingNotificationEvents(ctx context.Context, arg FindPendingNotificationEventsParams) ([]NotificationEvent, error)
	FindReportHistoryByPeriod(ctx context.Context, period string) (ReportHistory, error)
	FindResourceByHeartbeatSlug(ctx context.Context, heartbeatSlug pgtype.Text) (Resource, error)
	FindResourceByID(ctx context.Context, id string) (Resource, error)
	FindResourceIDsByTagName(ctx context.Context, arg FindResourceIDsByTagNameParams) ([]string, error)
	FindResourcesByComponentID(ctx context.Context, componentID pgtype.Text) ([]Resource, error)
	FindResourcesByIDs(ctx context.Context, dollar_1 []string) ([]Resource, error)
	FindSessionByID(ctx context.Context, id string) (Session, error)
	FindTagByID(ctx context.Context, id string) (Tag, error)
	FindTagByName(ctx context.Context, name string) (Tag, error)
	FindTagsByIDs(ctx context.Context, dollar_1 []string) ([]Tag, error)
	FindUnresolvedIncidents(ctx context.Context, arg FindUnresolvedIncidentsParams) ([]Incident, error)
	FindUptimeDailyAggForResource(ctx context.Context, arg FindUptimeDailyAggForResourceParams) ([]UptimeDailyAgg, error)
	FindUptimeDailyAggRange(ctx context.Context, arg FindUptimeDailyAggRangeParams) ([]UptimeDailyAgg, error)
	FindUserByEmail(ctx context.Context, email string) (User, error)
	FindUserByID(ctx context.Context, id string) (User, error)
	// Two aggregated counts in a single round-trip. CTE keeps the row scan
	// to one pass over the window.
	GetIncidentStatsPG(ctx context.Context, startedAt pgtype.Timestamptz) (GetIncidentStatsPGRow, error)
	GetIncidentUpdate(ctx context.Context, id string) (IncidentUpdate, error)
	GetRecentResponseTimes(ctx context.Context, arg GetRecentResponseTimesParams) ([]GetRecentResponseTimesRow, error)
	GetReportSettings(ctx context.Context) (ReportSetting, error)
	GetResourceCredentialByResourceID(ctx context.Context, resourceID string) (ResourceCredential, error)
	GetStatusPageSettings(ctx context.Context) (StatusPageSetting, error)
	HasActiveIncident(ctx context.Context) (bool, error)
	InsertHostMetric(ctx context.Context, arg InsertHostMetricParams) error
	LinkMaintenanceResource(ctx context.Context, arg LinkMaintenanceResourceParams) error
	// M2M: resource_notification_channels ---------------------------------------
	LinkResourceChannel(ctx context.Context, arg LinkResourceChannelParams) error
	// M2M: resource_tags ---------------------------------------------------------
	LinkResourceTag(ctx context.Context, arg LinkResourceTagParams) error
	ListAPIKeysByUserID(ctx context.Context, userID string) ([]ApiKey, error)
	ListActiveAnnouncements(ctx context.Context, active bool) ([]Announcement, error)
	ListActiveResources(ctx context.Context, arg ListActiveResourcesParams) ([]Resource, error)
	ListActiveSessionsByUser(ctx context.Context, userID string) ([]Session, error)
	ListChannelIDsByResourceID(ctx context.Context, resourceID string) ([]string, error)
	ListChannelsByResourceIDs(ctx context.Context, dollar_1 []string) ([]ListChannelsByResourceIDsRow, error)
	ListComponents(ctx context.Context, arg ListComponentsParams) ([]Component, error)
	// 1-to-1 preloads ------------------------------------------------------------
	ListComponentsByIDs(ctx context.Context, dollar_1 []string) ([]Component, error)
	ListCredentialsByResourceIDs(ctx context.Context, dollar_1 []string) ([]ResourceCredential, error)
	ListDashboards(ctx context.Context, arg ListDashboardsParams) ([]ListDashboardsRow, error)
	ListEscalationPolicies(ctx context.Context) ([]EscalationPolicy, error)
	ListEscalationStepsByPolicy(ctx context.Context, policyID string) ([]EscalationStep, error)
	ListHostCredentialsByHost(ctx context.Context, hostID string) ([]HostCredential, error)
	ListHostMetricsInRange(ctx context.Context, arg ListHostMetricsInRangeParams) ([]HostMetric, error)
	ListHosts(ctx context.Context, arg ListHostsParams) ([]Host, error)
	ListIncidentDiagnosticsByIncidentIDs(ctx context.Context, dollar_1 []string) ([]IncidentDiagnostic, error)
	ListIncidentEventSteps(ctx context.Context, arg ListIncidentEventStepsParams) ([]IncidentEventStep, error)
	ListIncidentUpdates(ctx context.Context, incidentID string) ([]IncidentUpdate, error)
	ListIncidents(ctx context.Context, arg ListIncidentsParams) ([]Incident, error)
	ListMaintenanceResourceIDsByMaintenanceID(ctx context.Context, maintenanceID string) ([]string, error)
	ListMaintenancesAll(ctx context.Context, arg ListMaintenancesAllParams) ([]Maintenance, error)
	ListMaintenancesByStatus(ctx context.Context, arg ListMaintenancesByStatusParams) ([]Maintenance, error)
	ListMonitoringActivities(ctx context.Context, arg ListMonitoringActivitiesParams) ([]MonitoringActivity, error)
	ListNotificationChannels(ctx context.Context, arg ListNotificationChannelsParams) ([]NotificationChannel, error)
	ListNotificationEvents(ctx context.Context, arg ListNotificationEventsParams) ([]NotificationEvent, error)
	ListNotificationsForUser(ctx context.Context, arg ListNotificationsForUserParams) ([]Notification, error)
	ListRecentReportHistory(ctx context.Context, lim int32) ([]ReportHistory, error)
	ListResources(ctx context.Context, arg ListResourcesParams) ([]Resource, error)
	ListResourcesByComponentID(ctx context.Context, componentID pgtype.Text) ([]Resource, error)
	ListScheduledResources(ctx context.Context) ([]Resource, error)
	ListTagIDsByResourceID(ctx context.Context, resourceID string) ([]string, error)
	ListTags(ctx context.Context, arg ListTagsParams) ([]Tag, error)
	ListTagsByResourceIDs(ctx context.Context, dollar_1 []string) ([]ListTagsByResourceIDsRow, error)
	MarkAllNotificationsReadForUser(ctx context.Context, arg MarkAllNotificationsReadForUserParams) (int64, error)
	MarkNotificationChannelFailure(ctx context.Context, arg MarkNotificationChannelFailureParams) error
	MarkNotificationChannelSent(ctx context.Context, arg MarkNotificationChannelSentParams) error
	MarkNotificationEventTerminal(ctx context.Context, arg MarkNotificationEventTerminalParams) (int64, error)
	MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (int64, error)
	MarkTwoFactorResetTokenUsed(ctx context.Context, arg MarkTwoFactorResetTokenUsedParams) (int64, error)
	NextEscalationPriority(ctx context.Context) (int32, error)
	Ping(ctx context.Context) (int32, error)
	ResourceCredentialExists(ctx context.Context, resourceID string) (int64, error)
	RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (int64, error)
	RevokeAllSessionsExcept(ctx context.Context, arg RevokeAllSessionsExceptParams) (int64, error)
	RevokeSession(ctx context.Context, arg RevokeSessionParams) (int64, error)
	SelectMonitoringActivityHourlyAggregateInputs(ctx context.Context, arg SelectMonitoringActivityHourlyAggregateInputsParams) ([]SelectMonitoringActivityHourlyAggregateInputsRow, error)
	SelectMonitoringActivitySuccessInWindow(ctx context.Context, arg SelectMonitoringActivitySuccessInWindowParams) ([]bool, error)
	SetEscalationPolicyPriority(ctx context.Context, arg SetEscalationPolicyPriorityParams) (int64, error)
	SetResourceHostID(ctx context.Context, arg SetResourceHostIDParams) (int64, error)
	SoftDeleteResource(ctx context.Context, id string) (int64, error)
	// One round-trip bulk aggregation grouped by resource. Used by the list path
	// to enrich each resource with its uptime ratio over a sliding window (30d).
	SumUptimeAggByResourcesSince(ctx context.Context, arg SumUptimeAggByResourcesSinceParams) ([]SumUptimeAggByResourcesSinceRow, error)
	TouchHostCredentialLastUsed(ctx context.Context, arg TouchHostCredentialLastUsedParams) error
	UnlinkMaintenanceResource(ctx context.Context, arg UnlinkMaintenanceResourceParams) error
	UnlinkResourceChannel(ctx context.Context, arg UnlinkResourceChannelParams) error
	UnlinkResourceTag(ctx context.Context, arg UnlinkResourceTagParams) error
	UpdateAPIKeyLastUsed(ctx context.Context, arg UpdateAPIKeyLastUsedParams) (int64, error)
	UpdateComponent(ctx context.Context, arg UpdateComponentParams) error
	UpdateComponentLastNotificationStatus(ctx context.Context, arg UpdateComponentLastNotificationStatusParams) (int64, error)
	UpdateDashboard(ctx context.Context, arg UpdateDashboardParams) (int64, error)
	UpdateDashboardWidgets(ctx context.Context, arg UpdateDashboardWidgetsParams) (int64, error)
	UpdateEscalationPolicy(ctx context.Context, arg UpdateEscalationPolicyParams) (int64, error)
	UpdateHostSnapshot(ctx context.Context, arg UpdateHostSnapshotParams) (int64, error)
	UpdateIncident(ctx context.Context, arg UpdateIncidentParams) (int64, error)
	UpdateIncidentDiagnostics(ctx context.Context, arg UpdateIncidentDiagnosticsParams) (int64, error)
	UpdateIncidentEventStep(ctx context.Context, arg UpdateIncidentEventStepParams) (int64, error)
	UpdateIncidentUpdate(ctx context.Context, arg UpdateIncidentUpdateParams) error
	UpdateMaintenance(ctx context.Context, arg UpdateMaintenanceParams) error
	UpdateNotificationChannel(ctx context.Context, arg UpdateNotificationChannelParams) (int64, error)
	UpdateNotificationEvent(ctx context.Context, arg UpdateNotificationEventParams) (int64, error)
	UpdateNotificationEventClaim(ctx context.Context, arg UpdateNotificationEventClaimParams) error
	UpdateResourceLastPingAt(ctx context.Context, arg UpdateResourceLastPingAtParams) (int64, error)
	UpdateResourceMain(ctx context.Context, arg UpdateResourceMainParams) (int64, error)
	UpdateResourceStatus(ctx context.Context, arg UpdateResourceStatusParams) (int64, error)
	UpdateSessionLastActive(ctx context.Context, arg UpdateSessionLastActiveParams) error
	UpdateStatusPageSettings(ctx context.Context, arg UpdateStatusPageSettingsParams) error
	UpdateTag(ctx context.Context, arg UpdateTagParams) (int64, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserLastLogin(ctx context.Context, id string) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserTwoFactorSecret(ctx context.Context, arg UpdateUserTwoFactorSecretParams) error
	UpsertReportSettings(ctx context.Context, arg UpsertReportSettingsParams) (ReportSetting, error)
	UpsertResourceCredential(ctx context.Context, arg UpsertResourceCredentialParams) error
	UpsertUptimeDailyAgg(ctx context.Context, arg UpsertUptimeDailyAggParams) error
}

var _ Querier = (*Queries)(nil)
