import { getAuthenticatedClient, request } from '@/core/http/client'
import type { SearchResult, SearchResultCategory } from '@/types'
import type { components } from '@ogoune/api-types'

// Response shape derived from the OpenAPI contract (spec 084 GET /api/v1/search),
// regenerated by `make gen-fe-types`. Keeps the FE aligned with the Go DTO.
type ContractSearchResponse =
  components['schemas']['github_com_denisakp_ogoune_internal_dto_v1.SearchResponse']

interface SearchEnvelope {
  data: ContractSearchResponse
}

export interface SearchOutcome {
  results: SearchResult[]
  durationMs: number
}

const KNOWN_CATEGORIES: SearchResultCategory[] = ['resource', 'incident', 'page']

function toCategory(c: string | undefined): SearchResultCategory {
  return KNOWN_CATEGORIES.includes(c as SearchResultCategory)
    ? (c as SearchResultCategory)
    : 'page'
}

/**
 * Command-palette search against `GET /api/v1/search` (spec 084).
 *
 * The contract returns a `deep_link` path string per hit; Vue Router accepts a
 * raw path as a `RouteLocationRaw`, so it maps directly onto `SearchResult.route`.
 * The server requires `q` to be at least 2 characters — callers must guard.
 *
 * On network/timeout/5xx this rejects (the shared Ky client normalizes the
 * error); callers should catch and fall back to a local search for resilience.
 */
export const searchPalette = async (
  q: string,
  opts?: { limit?: number; signal?: AbortSignal },
): Promise<SearchOutcome> => {
  const searchParams: Record<string, string | number> = { q }
  if (opts?.limit) searchParams.limit = opts.limit

  const res = await request<SearchEnvelope>(getAuthenticatedClient(), 'v1/search', {
    searchParams,
    ...(opts?.signal ? { signal: opts.signal } : {}),
  })

  const results: SearchResult[] = (res.data.results ?? []).map((r) => ({
    id: r.id ?? '',
    category: toCategory(r.category),
    label: r.label ?? '',
    meta: r.meta,
    route: r.deep_link ?? '/',
    score: 0,
  }))

  return { results, durationMs: res.data.query_duration_ms ?? 0 }
}
